FROM golang:1.22-alpine

WORKDIR /app



RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

RUN mkdir /.cache && chown -R 1000:1000 /.cache
RUN chown -R 1000:1000 /go

USER 1000

CMD ["air", "-c", "./.air.toml"]