externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    name: Noah Burnette
    url: https://github.com/nburnet1/gomes/issues
  description: Describes endpoints used by GoMES.
  license:
    name: MIT
    url: https://github.com/nburnet1/gomes/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: GoMES API
  version: "0.0"
paths:
  /enterprise:
    get:
      consumes:
      - application/json
      description: Get enterprise
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get enterprise
      tags:
      - enterprise
  /site:
    get:
      consumes:
      - application/json
      description: Get site
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get site
      tags:
      - site
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
