// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newEquipmentSpecification(db *gorm.DB, opts ...gen.DOOption) equipmentSpecification {
	_equipmentSpecification := equipmentSpecification{}

	_equipmentSpecification.equipmentSpecificationDo.UseDB(db, opts...)
	_equipmentSpecification.equipmentSpecificationDo.UseModel(&isa95.EquipmentSpecification{})

	tableName := _equipmentSpecification.equipmentSpecificationDo.TableName()
	_equipmentSpecification.ALL = field.NewAsterisk(tableName)
	_equipmentSpecification.ID = field.NewUint(tableName, "id")
	_equipmentSpecification.CreatedAt = field.NewTime(tableName, "created_at")
	_equipmentSpecification.UpdatedAt = field.NewTime(tableName, "updated_at")
	_equipmentSpecification.DeletedAt = field.NewField(tableName, "deleted_at")
	_equipmentSpecification.EquipmentClassID = field.NewUint(tableName, "equipment_class_id")
	_equipmentSpecification.EquipmentID = field.NewUint(tableName, "equipment_id")
	_equipmentSpecification.Description = field.NewString(tableName, "description")
	_equipmentSpecification.UseID = field.NewUint(tableName, "use_id")
	_equipmentSpecification.Quantity = field.NewString(tableName, "quantity")
	_equipmentSpecification.MeasurementID = field.NewUint(tableName, "measurement_id")
	_equipmentSpecification.Measurement = equipmentSpecificationBelongsToMeasurement{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Measurement", "isa95.Measurement"),
	}

	_equipmentSpecification.fillFieldMap()

	return _equipmentSpecification
}

type equipmentSpecification struct {
	equipmentSpecificationDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	EquipmentClassID field.Uint
	EquipmentID      field.Uint
	Description      field.String
	UseID            field.Uint
	Quantity         field.String
	MeasurementID    field.Uint
	Measurement      equipmentSpecificationBelongsToMeasurement

	fieldMap map[string]field.Expr
}

func (e equipmentSpecification) Table(newTableName string) *equipmentSpecification {
	e.equipmentSpecificationDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e equipmentSpecification) As(alias string) *equipmentSpecification {
	e.equipmentSpecificationDo.DO = *(e.equipmentSpecificationDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *equipmentSpecification) updateTableName(table string) *equipmentSpecification {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")
	e.EquipmentClassID = field.NewUint(table, "equipment_class_id")
	e.EquipmentID = field.NewUint(table, "equipment_id")
	e.Description = field.NewString(table, "description")
	e.UseID = field.NewUint(table, "use_id")
	e.Quantity = field.NewString(table, "quantity")
	e.MeasurementID = field.NewUint(table, "measurement_id")

	e.fillFieldMap()

	return e
}

func (e *equipmentSpecification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *equipmentSpecification) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
	e.fieldMap["equipment_class_id"] = e.EquipmentClassID
	e.fieldMap["equipment_id"] = e.EquipmentID
	e.fieldMap["description"] = e.Description
	e.fieldMap["use_id"] = e.UseID
	e.fieldMap["quantity"] = e.Quantity
	e.fieldMap["measurement_id"] = e.MeasurementID

}

func (e equipmentSpecification) clone(db *gorm.DB) equipmentSpecification {
	e.equipmentSpecificationDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e equipmentSpecification) replaceDB(db *gorm.DB) equipmentSpecification {
	e.equipmentSpecificationDo.ReplaceDB(db)
	return e
}

type equipmentSpecificationBelongsToMeasurement struct {
	db *gorm.DB

	field.RelationField
}

func (a equipmentSpecificationBelongsToMeasurement) Where(conds ...field.Expr) *equipmentSpecificationBelongsToMeasurement {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a equipmentSpecificationBelongsToMeasurement) WithContext(ctx context.Context) *equipmentSpecificationBelongsToMeasurement {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a equipmentSpecificationBelongsToMeasurement) Session(session *gorm.Session) *equipmentSpecificationBelongsToMeasurement {
	a.db = a.db.Session(session)
	return &a
}

func (a equipmentSpecificationBelongsToMeasurement) Model(m *isa95.EquipmentSpecification) *equipmentSpecificationBelongsToMeasurementTx {
	return &equipmentSpecificationBelongsToMeasurementTx{a.db.Model(m).Association(a.Name())}
}

type equipmentSpecificationBelongsToMeasurementTx struct{ tx *gorm.Association }

func (a equipmentSpecificationBelongsToMeasurementTx) Find() (result *isa95.Measurement, err error) {
	return result, a.tx.Find(&result)
}

func (a equipmentSpecificationBelongsToMeasurementTx) Append(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a equipmentSpecificationBelongsToMeasurementTx) Replace(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a equipmentSpecificationBelongsToMeasurementTx) Delete(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a equipmentSpecificationBelongsToMeasurementTx) Clear() error {
	return a.tx.Clear()
}

func (a equipmentSpecificationBelongsToMeasurementTx) Count() int64 {
	return a.tx.Count()
}

type equipmentSpecificationDo struct{ gen.DO }

func (e equipmentSpecificationDo) Debug() *equipmentSpecificationDo {
	return e.withDO(e.DO.Debug())
}

func (e equipmentSpecificationDo) WithContext(ctx context.Context) *equipmentSpecificationDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e equipmentSpecificationDo) ReadDB() *equipmentSpecificationDo {
	return e.Clauses(dbresolver.Read)
}

func (e equipmentSpecificationDo) WriteDB() *equipmentSpecificationDo {
	return e.Clauses(dbresolver.Write)
}

func (e equipmentSpecificationDo) Session(config *gorm.Session) *equipmentSpecificationDo {
	return e.withDO(e.DO.Session(config))
}

func (e equipmentSpecificationDo) Clauses(conds ...clause.Expression) *equipmentSpecificationDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e equipmentSpecificationDo) Returning(value interface{}, columns ...string) *equipmentSpecificationDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e equipmentSpecificationDo) Not(conds ...gen.Condition) *equipmentSpecificationDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e equipmentSpecificationDo) Or(conds ...gen.Condition) *equipmentSpecificationDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e equipmentSpecificationDo) Select(conds ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e equipmentSpecificationDo) Where(conds ...gen.Condition) *equipmentSpecificationDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e equipmentSpecificationDo) Order(conds ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e equipmentSpecificationDo) Distinct(cols ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e equipmentSpecificationDo) Omit(cols ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e equipmentSpecificationDo) Join(table schema.Tabler, on ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e equipmentSpecificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e equipmentSpecificationDo) RightJoin(table schema.Tabler, on ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e equipmentSpecificationDo) Group(cols ...field.Expr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e equipmentSpecificationDo) Having(conds ...gen.Condition) *equipmentSpecificationDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e equipmentSpecificationDo) Limit(limit int) *equipmentSpecificationDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e equipmentSpecificationDo) Offset(offset int) *equipmentSpecificationDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e equipmentSpecificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *equipmentSpecificationDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e equipmentSpecificationDo) Unscoped() *equipmentSpecificationDo {
	return e.withDO(e.DO.Unscoped())
}

func (e equipmentSpecificationDo) Create(values ...*isa95.EquipmentSpecification) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e equipmentSpecificationDo) CreateInBatches(values []*isa95.EquipmentSpecification, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e equipmentSpecificationDo) Save(values ...*isa95.EquipmentSpecification) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e equipmentSpecificationDo) First() (*isa95.EquipmentSpecification, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSpecification), nil
	}
}

func (e equipmentSpecificationDo) Take() (*isa95.EquipmentSpecification, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSpecification), nil
	}
}

func (e equipmentSpecificationDo) Last() (*isa95.EquipmentSpecification, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSpecification), nil
	}
}

func (e equipmentSpecificationDo) Find() ([]*isa95.EquipmentSpecification, error) {
	result, err := e.DO.Find()
	return result.([]*isa95.EquipmentSpecification), err
}

func (e equipmentSpecificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.EquipmentSpecification, err error) {
	buf := make([]*isa95.EquipmentSpecification, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e equipmentSpecificationDo) FindInBatches(result *[]*isa95.EquipmentSpecification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e equipmentSpecificationDo) Attrs(attrs ...field.AssignExpr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e equipmentSpecificationDo) Assign(attrs ...field.AssignExpr) *equipmentSpecificationDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e equipmentSpecificationDo) Joins(fields ...field.RelationField) *equipmentSpecificationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e equipmentSpecificationDo) Preload(fields ...field.RelationField) *equipmentSpecificationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e equipmentSpecificationDo) FirstOrInit() (*isa95.EquipmentSpecification, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSpecification), nil
	}
}

func (e equipmentSpecificationDo) FirstOrCreate() (*isa95.EquipmentSpecification, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSpecification), nil
	}
}

func (e equipmentSpecificationDo) FindByPage(offset int, limit int) (result []*isa95.EquipmentSpecification, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e equipmentSpecificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e equipmentSpecificationDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e equipmentSpecificationDo) Delete(models ...*isa95.EquipmentSpecification) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *equipmentSpecificationDo) withDO(do gen.Dao) *equipmentSpecificationDo {
	e.DO = *do.(*gen.DO)
	return e
}
