// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newEquipmentClass(db *gorm.DB, opts ...gen.DOOption) equipmentClass {
	_equipmentClass := equipmentClass{}

	_equipmentClass.equipmentClassDo.UseDB(db, opts...)
	_equipmentClass.equipmentClassDo.UseModel(&isa95.EquipmentClass{})

	tableName := _equipmentClass.equipmentClassDo.TableName()
	_equipmentClass.ALL = field.NewAsterisk(tableName)
	_equipmentClass.ID = field.NewUint(tableName, "id")
	_equipmentClass.CreatedAt = field.NewTime(tableName, "created_at")
	_equipmentClass.UpdatedAt = field.NewTime(tableName, "updated_at")
	_equipmentClass.DeletedAt = field.NewField(tableName, "deleted_at")
	_equipmentClass.Description = field.NewString(tableName, "description")
	_equipmentClass.LevelID = field.NewUint(tableName, "level_id")

	_equipmentClass.fillFieldMap()

	return _equipmentClass
}

type equipmentClass struct {
	equipmentClassDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Description field.String
	LevelID     field.Uint

	fieldMap map[string]field.Expr
}

func (e equipmentClass) Table(newTableName string) *equipmentClass {
	e.equipmentClassDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e equipmentClass) As(alias string) *equipmentClass {
	e.equipmentClassDo.DO = *(e.equipmentClassDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *equipmentClass) updateTableName(table string) *equipmentClass {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")
	e.Description = field.NewString(table, "description")
	e.LevelID = field.NewUint(table, "level_id")

	e.fillFieldMap()

	return e
}

func (e *equipmentClass) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *equipmentClass) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 6)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
	e.fieldMap["description"] = e.Description
	e.fieldMap["level_id"] = e.LevelID
}

func (e equipmentClass) clone(db *gorm.DB) equipmentClass {
	e.equipmentClassDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e equipmentClass) replaceDB(db *gorm.DB) equipmentClass {
	e.equipmentClassDo.ReplaceDB(db)
	return e
}

type equipmentClassDo struct{ gen.DO }

func (e equipmentClassDo) Debug() *equipmentClassDo {
	return e.withDO(e.DO.Debug())
}

func (e equipmentClassDo) WithContext(ctx context.Context) *equipmentClassDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e equipmentClassDo) ReadDB() *equipmentClassDo {
	return e.Clauses(dbresolver.Read)
}

func (e equipmentClassDo) WriteDB() *equipmentClassDo {
	return e.Clauses(dbresolver.Write)
}

func (e equipmentClassDo) Session(config *gorm.Session) *equipmentClassDo {
	return e.withDO(e.DO.Session(config))
}

func (e equipmentClassDo) Clauses(conds ...clause.Expression) *equipmentClassDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e equipmentClassDo) Returning(value interface{}, columns ...string) *equipmentClassDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e equipmentClassDo) Not(conds ...gen.Condition) *equipmentClassDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e equipmentClassDo) Or(conds ...gen.Condition) *equipmentClassDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e equipmentClassDo) Select(conds ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e equipmentClassDo) Where(conds ...gen.Condition) *equipmentClassDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e equipmentClassDo) Order(conds ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e equipmentClassDo) Distinct(cols ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e equipmentClassDo) Omit(cols ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e equipmentClassDo) Join(table schema.Tabler, on ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e equipmentClassDo) LeftJoin(table schema.Tabler, on ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e equipmentClassDo) RightJoin(table schema.Tabler, on ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e equipmentClassDo) Group(cols ...field.Expr) *equipmentClassDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e equipmentClassDo) Having(conds ...gen.Condition) *equipmentClassDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e equipmentClassDo) Limit(limit int) *equipmentClassDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e equipmentClassDo) Offset(offset int) *equipmentClassDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e equipmentClassDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *equipmentClassDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e equipmentClassDo) Unscoped() *equipmentClassDo {
	return e.withDO(e.DO.Unscoped())
}

func (e equipmentClassDo) Create(values ...*isa95.EquipmentClass) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e equipmentClassDo) CreateInBatches(values []*isa95.EquipmentClass, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e equipmentClassDo) Save(values ...*isa95.EquipmentClass) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e equipmentClassDo) First() (*isa95.EquipmentClass, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentClass), nil
	}
}

func (e equipmentClassDo) Take() (*isa95.EquipmentClass, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentClass), nil
	}
}

func (e equipmentClassDo) Last() (*isa95.EquipmentClass, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentClass), nil
	}
}

func (e equipmentClassDo) Find() ([]*isa95.EquipmentClass, error) {
	result, err := e.DO.Find()
	return result.([]*isa95.EquipmentClass), err
}

func (e equipmentClassDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.EquipmentClass, err error) {
	buf := make([]*isa95.EquipmentClass, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e equipmentClassDo) FindInBatches(result *[]*isa95.EquipmentClass, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e equipmentClassDo) Attrs(attrs ...field.AssignExpr) *equipmentClassDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e equipmentClassDo) Assign(attrs ...field.AssignExpr) *equipmentClassDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e equipmentClassDo) Joins(fields ...field.RelationField) *equipmentClassDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e equipmentClassDo) Preload(fields ...field.RelationField) *equipmentClassDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e equipmentClassDo) FirstOrInit() (*isa95.EquipmentClass, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentClass), nil
	}
}

func (e equipmentClassDo) FirstOrCreate() (*isa95.EquipmentClass, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentClass), nil
	}
}

func (e equipmentClassDo) FindByPage(offset int, limit int) (result []*isa95.EquipmentClass, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e equipmentClassDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e equipmentClassDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e equipmentClassDo) Delete(models ...*isa95.EquipmentClass) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *equipmentClassDo) withDO(do gen.Dao) *equipmentClassDo {
	e.DO = *do.(*gen.DO)
	return e
}
