// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newEquipmentSegment(db *gorm.DB, opts ...gen.DOOption) equipmentSegment {
	_equipmentSegment := equipmentSegment{}

	_equipmentSegment.equipmentSegmentDo.UseDB(db, opts...)
	_equipmentSegment.equipmentSegmentDo.UseModel(&isa95.EquipmentSegment{})

	tableName := _equipmentSegment.equipmentSegmentDo.TableName()
	_equipmentSegment.ALL = field.NewAsterisk(tableName)
	_equipmentSegment.ID = field.NewUint(tableName, "id")
	_equipmentSegment.CreatedAt = field.NewTime(tableName, "created_at")
	_equipmentSegment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_equipmentSegment.DeletedAt = field.NewField(tableName, "deleted_at")
	_equipmentSegment.EquipmentClassID = field.NewUint(tableName, "equipment_class_id")
	_equipmentSegment.Description = field.NewString(tableName, "description")
	_equipmentSegment.Quantity = field.NewString(tableName, "quantity")
	_equipmentSegment.MeasurementID = field.NewUint(tableName, "measurement_id")
	_equipmentSegment.UseID = field.NewUint(tableName, "use_id")

	_equipmentSegment.fillFieldMap()

	return _equipmentSegment
}

type equipmentSegment struct {
	equipmentSegmentDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	EquipmentClassID field.Uint
	Description      field.String
	Quantity         field.String
	MeasurementID    field.Uint
	UseID            field.Uint

	fieldMap map[string]field.Expr
}

func (e equipmentSegment) Table(newTableName string) *equipmentSegment {
	e.equipmentSegmentDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e equipmentSegment) As(alias string) *equipmentSegment {
	e.equipmentSegmentDo.DO = *(e.equipmentSegmentDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *equipmentSegment) updateTableName(table string) *equipmentSegment {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")
	e.EquipmentClassID = field.NewUint(table, "equipment_class_id")
	e.Description = field.NewString(table, "description")
	e.Quantity = field.NewString(table, "quantity")
	e.MeasurementID = field.NewUint(table, "measurement_id")
	e.UseID = field.NewUint(table, "use_id")

	e.fillFieldMap()

	return e
}

func (e *equipmentSegment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *equipmentSegment) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
	e.fieldMap["equipment_class_id"] = e.EquipmentClassID
	e.fieldMap["description"] = e.Description
	e.fieldMap["quantity"] = e.Quantity
	e.fieldMap["measurement_id"] = e.MeasurementID
	e.fieldMap["use_id"] = e.UseID
}

func (e equipmentSegment) clone(db *gorm.DB) equipmentSegment {
	e.equipmentSegmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e equipmentSegment) replaceDB(db *gorm.DB) equipmentSegment {
	e.equipmentSegmentDo.ReplaceDB(db)
	return e
}

type equipmentSegmentDo struct{ gen.DO }

func (e equipmentSegmentDo) Debug() *equipmentSegmentDo {
	return e.withDO(e.DO.Debug())
}

func (e equipmentSegmentDo) WithContext(ctx context.Context) *equipmentSegmentDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e equipmentSegmentDo) ReadDB() *equipmentSegmentDo {
	return e.Clauses(dbresolver.Read)
}

func (e equipmentSegmentDo) WriteDB() *equipmentSegmentDo {
	return e.Clauses(dbresolver.Write)
}

func (e equipmentSegmentDo) Session(config *gorm.Session) *equipmentSegmentDo {
	return e.withDO(e.DO.Session(config))
}

func (e equipmentSegmentDo) Clauses(conds ...clause.Expression) *equipmentSegmentDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e equipmentSegmentDo) Returning(value interface{}, columns ...string) *equipmentSegmentDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e equipmentSegmentDo) Not(conds ...gen.Condition) *equipmentSegmentDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e equipmentSegmentDo) Or(conds ...gen.Condition) *equipmentSegmentDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e equipmentSegmentDo) Select(conds ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e equipmentSegmentDo) Where(conds ...gen.Condition) *equipmentSegmentDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e equipmentSegmentDo) Order(conds ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e equipmentSegmentDo) Distinct(cols ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e equipmentSegmentDo) Omit(cols ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e equipmentSegmentDo) Join(table schema.Tabler, on ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e equipmentSegmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e equipmentSegmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e equipmentSegmentDo) Group(cols ...field.Expr) *equipmentSegmentDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e equipmentSegmentDo) Having(conds ...gen.Condition) *equipmentSegmentDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e equipmentSegmentDo) Limit(limit int) *equipmentSegmentDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e equipmentSegmentDo) Offset(offset int) *equipmentSegmentDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e equipmentSegmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *equipmentSegmentDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e equipmentSegmentDo) Unscoped() *equipmentSegmentDo {
	return e.withDO(e.DO.Unscoped())
}

func (e equipmentSegmentDo) Create(values ...*isa95.EquipmentSegment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e equipmentSegmentDo) CreateInBatches(values []*isa95.EquipmentSegment, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e equipmentSegmentDo) Save(values ...*isa95.EquipmentSegment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e equipmentSegmentDo) First() (*isa95.EquipmentSegment, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSegment), nil
	}
}

func (e equipmentSegmentDo) Take() (*isa95.EquipmentSegment, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSegment), nil
	}
}

func (e equipmentSegmentDo) Last() (*isa95.EquipmentSegment, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSegment), nil
	}
}

func (e equipmentSegmentDo) Find() ([]*isa95.EquipmentSegment, error) {
	result, err := e.DO.Find()
	return result.([]*isa95.EquipmentSegment), err
}

func (e equipmentSegmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.EquipmentSegment, err error) {
	buf := make([]*isa95.EquipmentSegment, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e equipmentSegmentDo) FindInBatches(result *[]*isa95.EquipmentSegment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e equipmentSegmentDo) Attrs(attrs ...field.AssignExpr) *equipmentSegmentDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e equipmentSegmentDo) Assign(attrs ...field.AssignExpr) *equipmentSegmentDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e equipmentSegmentDo) Joins(fields ...field.RelationField) *equipmentSegmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e equipmentSegmentDo) Preload(fields ...field.RelationField) *equipmentSegmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e equipmentSegmentDo) FirstOrInit() (*isa95.EquipmentSegment, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSegment), nil
	}
}

func (e equipmentSegmentDo) FirstOrCreate() (*isa95.EquipmentSegment, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.EquipmentSegment), nil
	}
}

func (e equipmentSegmentDo) FindByPage(offset int, limit int) (result []*isa95.EquipmentSegment, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e equipmentSegmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e equipmentSegmentDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e equipmentSegmentDo) Delete(models ...*isa95.EquipmentSegment) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *equipmentSegmentDo) withDO(do gen.Dao) *equipmentSegmentDo {
	e.DO = *do.(*gen.DO)
	return e
}
