// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newEquipment(db *gorm.DB, opts ...gen.DOOption) equipment {
	_equipment := equipment{}

	_equipment.equipmentDo.UseDB(db, opts...)
	_equipment.equipmentDo.UseModel(&isa95.Equipment{})

	tableName := _equipment.equipmentDo.TableName()
	_equipment.ALL = field.NewAsterisk(tableName)
	_equipment.ID = field.NewUint(tableName, "id")
	_equipment.CreatedAt = field.NewTime(tableName, "created_at")
	_equipment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_equipment.DeletedAt = field.NewField(tableName, "deleted_at")
	_equipment.Description = field.NewString(tableName, "description")
	_equipment.LevelID = field.NewUint(tableName, "level_id")
	_equipment.Level = equipmentBelongsToLevel{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Level", "isa95.Level"),
		LevelLookup: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Level.LevelLookup", "isa95.LevelLookup"),
		},
	}

	_equipment.fillFieldMap()

	return _equipment
}

type equipment struct {
	equipmentDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Description field.String
	LevelID     field.Uint
	Level       equipmentBelongsToLevel

	fieldMap map[string]field.Expr
}

func (e equipment) Table(newTableName string) *equipment {
	e.equipmentDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e equipment) As(alias string) *equipment {
	e.equipmentDo.DO = *(e.equipmentDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *equipment) updateTableName(table string) *equipment {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")
	e.Description = field.NewString(table, "description")
	e.LevelID = field.NewUint(table, "level_id")

	e.fillFieldMap()

	return e
}

func (e *equipment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *equipment) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 7)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
	e.fieldMap["description"] = e.Description
	e.fieldMap["level_id"] = e.LevelID

}

func (e equipment) clone(db *gorm.DB) equipment {
	e.equipmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e equipment) replaceDB(db *gorm.DB) equipment {
	e.equipmentDo.ReplaceDB(db)
	return e
}

type equipmentBelongsToLevel struct {
	db *gorm.DB

	field.RelationField

	LevelLookup struct {
		field.RelationField
	}
}

func (a equipmentBelongsToLevel) Where(conds ...field.Expr) *equipmentBelongsToLevel {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a equipmentBelongsToLevel) WithContext(ctx context.Context) *equipmentBelongsToLevel {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a equipmentBelongsToLevel) Session(session *gorm.Session) *equipmentBelongsToLevel {
	a.db = a.db.Session(session)
	return &a
}

func (a equipmentBelongsToLevel) Model(m *isa95.Equipment) *equipmentBelongsToLevelTx {
	return &equipmentBelongsToLevelTx{a.db.Model(m).Association(a.Name())}
}

type equipmentBelongsToLevelTx struct{ tx *gorm.Association }

func (a equipmentBelongsToLevelTx) Find() (result *isa95.Level, err error) {
	return result, a.tx.Find(&result)
}

func (a equipmentBelongsToLevelTx) Append(values ...*isa95.Level) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a equipmentBelongsToLevelTx) Replace(values ...*isa95.Level) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a equipmentBelongsToLevelTx) Delete(values ...*isa95.Level) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a equipmentBelongsToLevelTx) Clear() error {
	return a.tx.Clear()
}

func (a equipmentBelongsToLevelTx) Count() int64 {
	return a.tx.Count()
}

type equipmentDo struct{ gen.DO }

func (e equipmentDo) Debug() *equipmentDo {
	return e.withDO(e.DO.Debug())
}

func (e equipmentDo) WithContext(ctx context.Context) *equipmentDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e equipmentDo) ReadDB() *equipmentDo {
	return e.Clauses(dbresolver.Read)
}

func (e equipmentDo) WriteDB() *equipmentDo {
	return e.Clauses(dbresolver.Write)
}

func (e equipmentDo) Session(config *gorm.Session) *equipmentDo {
	return e.withDO(e.DO.Session(config))
}

func (e equipmentDo) Clauses(conds ...clause.Expression) *equipmentDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e equipmentDo) Returning(value interface{}, columns ...string) *equipmentDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e equipmentDo) Not(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e equipmentDo) Or(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e equipmentDo) Select(conds ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e equipmentDo) Where(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e equipmentDo) Order(conds ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e equipmentDo) Distinct(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e equipmentDo) Omit(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e equipmentDo) Join(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e equipmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e equipmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e equipmentDo) Group(cols ...field.Expr) *equipmentDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e equipmentDo) Having(conds ...gen.Condition) *equipmentDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e equipmentDo) Limit(limit int) *equipmentDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e equipmentDo) Offset(offset int) *equipmentDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e equipmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *equipmentDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e equipmentDo) Unscoped() *equipmentDo {
	return e.withDO(e.DO.Unscoped())
}

func (e equipmentDo) Create(values ...*isa95.Equipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e equipmentDo) CreateInBatches(values []*isa95.Equipment, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e equipmentDo) Save(values ...*isa95.Equipment) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e equipmentDo) First() (*isa95.Equipment, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.Equipment), nil
	}
}

func (e equipmentDo) Take() (*isa95.Equipment, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.Equipment), nil
	}
}

func (e equipmentDo) Last() (*isa95.Equipment, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.Equipment), nil
	}
}

func (e equipmentDo) Find() ([]*isa95.Equipment, error) {
	result, err := e.DO.Find()
	return result.([]*isa95.Equipment), err
}

func (e equipmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.Equipment, err error) {
	buf := make([]*isa95.Equipment, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e equipmentDo) FindInBatches(result *[]*isa95.Equipment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e equipmentDo) Attrs(attrs ...field.AssignExpr) *equipmentDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e equipmentDo) Assign(attrs ...field.AssignExpr) *equipmentDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e equipmentDo) Joins(fields ...field.RelationField) *equipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e equipmentDo) Preload(fields ...field.RelationField) *equipmentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e equipmentDo) FirstOrInit() (*isa95.Equipment, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.Equipment), nil
	}
}

func (e equipmentDo) FirstOrCreate() (*isa95.Equipment, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.Equipment), nil
	}
}

func (e equipmentDo) FindByPage(offset int, limit int) (result []*isa95.Equipment, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e equipmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e equipmentDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e equipmentDo) Delete(models ...*isa95.Equipment) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *equipmentDo) withDO(do gen.Dao) *equipmentDo {
	e.DO = *do.(*gen.DO)
	return e
}
