// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newMaterialSpecification(db *gorm.DB, opts ...gen.DOOption) materialSpecification {
	_materialSpecification := materialSpecification{}

	_materialSpecification.materialSpecificationDo.UseDB(db, opts...)
	_materialSpecification.materialSpecificationDo.UseModel(&isa95.MaterialSpecification{})

	tableName := _materialSpecification.materialSpecificationDo.TableName()
	_materialSpecification.ALL = field.NewAsterisk(tableName)
	_materialSpecification.ID = field.NewUint(tableName, "id")
	_materialSpecification.CreatedAt = field.NewTime(tableName, "created_at")
	_materialSpecification.UpdatedAt = field.NewTime(tableName, "updated_at")
	_materialSpecification.DeletedAt = field.NewField(tableName, "deleted_at")
	_materialSpecification.MaterialClassID = field.NewUint(tableName, "material_class_id")
	_materialSpecification.MaterialDefinitionID = field.NewUint(tableName, "material_definition_id")
	_materialSpecification.Description = field.NewString(tableName, "description")
	_materialSpecification.UseID = field.NewUint(tableName, "use_id")
	_materialSpecification.Quantity = field.NewString(tableName, "quantity")
	_materialSpecification.MeasurementID = field.NewUint(tableName, "measurement_id")
	_materialSpecification.AssemblyTypeID = field.NewUint(tableName, "assembly_type_id")
	_materialSpecification.AssemblyRelationshipID = field.NewUint(tableName, "assembly_relationship_id")

	_materialSpecification.fillFieldMap()

	return _materialSpecification
}

type materialSpecification struct {
	materialSpecificationDo

	ALL                    field.Asterisk
	ID                     field.Uint
	CreatedAt              field.Time
	UpdatedAt              field.Time
	DeletedAt              field.Field
	MaterialClassID        field.Uint
	MaterialDefinitionID   field.Uint
	Description            field.String
	UseID                  field.Uint
	Quantity               field.String
	MeasurementID          field.Uint
	AssemblyTypeID         field.Uint
	AssemblyRelationshipID field.Uint

	fieldMap map[string]field.Expr
}

func (m materialSpecification) Table(newTableName string) *materialSpecification {
	m.materialSpecificationDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m materialSpecification) As(alias string) *materialSpecification {
	m.materialSpecificationDo.DO = *(m.materialSpecificationDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *materialSpecification) updateTableName(table string) *materialSpecification {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MaterialClassID = field.NewUint(table, "material_class_id")
	m.MaterialDefinitionID = field.NewUint(table, "material_definition_id")
	m.Description = field.NewString(table, "description")
	m.UseID = field.NewUint(table, "use_id")
	m.Quantity = field.NewString(table, "quantity")
	m.MeasurementID = field.NewUint(table, "measurement_id")
	m.AssemblyTypeID = field.NewUint(table, "assembly_type_id")
	m.AssemblyRelationshipID = field.NewUint(table, "assembly_relationship_id")

	m.fillFieldMap()

	return m
}

func (m *materialSpecification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *materialSpecification) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["material_class_id"] = m.MaterialClassID
	m.fieldMap["material_definition_id"] = m.MaterialDefinitionID
	m.fieldMap["description"] = m.Description
	m.fieldMap["use_id"] = m.UseID
	m.fieldMap["quantity"] = m.Quantity
	m.fieldMap["measurement_id"] = m.MeasurementID
	m.fieldMap["assembly_type_id"] = m.AssemblyTypeID
	m.fieldMap["assembly_relationship_id"] = m.AssemblyRelationshipID
}

func (m materialSpecification) clone(db *gorm.DB) materialSpecification {
	m.materialSpecificationDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m materialSpecification) replaceDB(db *gorm.DB) materialSpecification {
	m.materialSpecificationDo.ReplaceDB(db)
	return m
}

type materialSpecificationDo struct{ gen.DO }

func (m materialSpecificationDo) Debug() *materialSpecificationDo {
	return m.withDO(m.DO.Debug())
}

func (m materialSpecificationDo) WithContext(ctx context.Context) *materialSpecificationDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m materialSpecificationDo) ReadDB() *materialSpecificationDo {
	return m.Clauses(dbresolver.Read)
}

func (m materialSpecificationDo) WriteDB() *materialSpecificationDo {
	return m.Clauses(dbresolver.Write)
}

func (m materialSpecificationDo) Session(config *gorm.Session) *materialSpecificationDo {
	return m.withDO(m.DO.Session(config))
}

func (m materialSpecificationDo) Clauses(conds ...clause.Expression) *materialSpecificationDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m materialSpecificationDo) Returning(value interface{}, columns ...string) *materialSpecificationDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m materialSpecificationDo) Not(conds ...gen.Condition) *materialSpecificationDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m materialSpecificationDo) Or(conds ...gen.Condition) *materialSpecificationDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m materialSpecificationDo) Select(conds ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m materialSpecificationDo) Where(conds ...gen.Condition) *materialSpecificationDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m materialSpecificationDo) Order(conds ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m materialSpecificationDo) Distinct(cols ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m materialSpecificationDo) Omit(cols ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m materialSpecificationDo) Join(table schema.Tabler, on ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m materialSpecificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m materialSpecificationDo) RightJoin(table schema.Tabler, on ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m materialSpecificationDo) Group(cols ...field.Expr) *materialSpecificationDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m materialSpecificationDo) Having(conds ...gen.Condition) *materialSpecificationDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m materialSpecificationDo) Limit(limit int) *materialSpecificationDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m materialSpecificationDo) Offset(offset int) *materialSpecificationDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m materialSpecificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *materialSpecificationDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m materialSpecificationDo) Unscoped() *materialSpecificationDo {
	return m.withDO(m.DO.Unscoped())
}

func (m materialSpecificationDo) Create(values ...*isa95.MaterialSpecification) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m materialSpecificationDo) CreateInBatches(values []*isa95.MaterialSpecification, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m materialSpecificationDo) Save(values ...*isa95.MaterialSpecification) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m materialSpecificationDo) First() (*isa95.MaterialSpecification, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.MaterialSpecification), nil
	}
}

func (m materialSpecificationDo) Take() (*isa95.MaterialSpecification, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.MaterialSpecification), nil
	}
}

func (m materialSpecificationDo) Last() (*isa95.MaterialSpecification, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.MaterialSpecification), nil
	}
}

func (m materialSpecificationDo) Find() ([]*isa95.MaterialSpecification, error) {
	result, err := m.DO.Find()
	return result.([]*isa95.MaterialSpecification), err
}

func (m materialSpecificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.MaterialSpecification, err error) {
	buf := make([]*isa95.MaterialSpecification, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m materialSpecificationDo) FindInBatches(result *[]*isa95.MaterialSpecification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m materialSpecificationDo) Attrs(attrs ...field.AssignExpr) *materialSpecificationDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m materialSpecificationDo) Assign(attrs ...field.AssignExpr) *materialSpecificationDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m materialSpecificationDo) Joins(fields ...field.RelationField) *materialSpecificationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m materialSpecificationDo) Preload(fields ...field.RelationField) *materialSpecificationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m materialSpecificationDo) FirstOrInit() (*isa95.MaterialSpecification, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.MaterialSpecification), nil
	}
}

func (m materialSpecificationDo) FirstOrCreate() (*isa95.MaterialSpecification, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.MaterialSpecification), nil
	}
}

func (m materialSpecificationDo) FindByPage(offset int, limit int) (result []*isa95.MaterialSpecification, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m materialSpecificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m materialSpecificationDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m materialSpecificationDo) Delete(models ...*isa95.MaterialSpecification) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *materialSpecificationDo) withDO(do gen.Dao) *materialSpecificationDo {
	m.DO = *do.(*gen.DO)
	return m
}
