// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newOperationMaterialBillItem(db *gorm.DB, opts ...gen.DOOption) operationMaterialBillItem {
	_operationMaterialBillItem := operationMaterialBillItem{}

	_operationMaterialBillItem.operationMaterialBillItemDo.UseDB(db, opts...)
	_operationMaterialBillItem.operationMaterialBillItemDo.UseModel(&isa95.OperationMaterialBillItem{})

	tableName := _operationMaterialBillItem.operationMaterialBillItemDo.TableName()
	_operationMaterialBillItem.ALL = field.NewAsterisk(tableName)
	_operationMaterialBillItem.ID = field.NewUint(tableName, "id")
	_operationMaterialBillItem.CreatedAt = field.NewTime(tableName, "created_at")
	_operationMaterialBillItem.UpdatedAt = field.NewTime(tableName, "updated_at")
	_operationMaterialBillItem.DeletedAt = field.NewField(tableName, "deleted_at")
	_operationMaterialBillItem.Code = field.NewString(tableName, "code")
	_operationMaterialBillItem.Description = field.NewString(tableName, "description")
	_operationMaterialBillItem.MaterialClassID = field.NewUint(tableName, "material_class_id")
	_operationMaterialBillItem.MaterialDefinitionID = field.NewUint(tableName, "material_definition_id")
	_operationMaterialBillItem.UseID = field.NewUint(tableName, "use_id")
	_operationMaterialBillItem.AssemblyTypeID = field.NewUint(tableName, "assembly_type_id")
	_operationMaterialBillItem.AssemblyRelationshipID = field.NewUint(tableName, "assembly_relationship_id")
	_operationMaterialBillItem.Quantity = field.NewString(tableName, "quantity")
	_operationMaterialBillItem.MeasurementID = field.NewUint(tableName, "measurement_id")

	_operationMaterialBillItem.fillFieldMap()

	return _operationMaterialBillItem
}

type operationMaterialBillItem struct {
	operationMaterialBillItemDo

	ALL                    field.Asterisk
	ID                     field.Uint
	CreatedAt              field.Time
	UpdatedAt              field.Time
	DeletedAt              field.Field
	Code                   field.String
	Description            field.String
	MaterialClassID        field.Uint
	MaterialDefinitionID   field.Uint
	UseID                  field.Uint
	AssemblyTypeID         field.Uint
	AssemblyRelationshipID field.Uint
	Quantity               field.String
	MeasurementID          field.Uint

	fieldMap map[string]field.Expr
}

func (o operationMaterialBillItem) Table(newTableName string) *operationMaterialBillItem {
	o.operationMaterialBillItemDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o operationMaterialBillItem) As(alias string) *operationMaterialBillItem {
	o.operationMaterialBillItemDo.DO = *(o.operationMaterialBillItemDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *operationMaterialBillItem) updateTableName(table string) *operationMaterialBillItem {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewUint(table, "id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.Code = field.NewString(table, "code")
	o.Description = field.NewString(table, "description")
	o.MaterialClassID = field.NewUint(table, "material_class_id")
	o.MaterialDefinitionID = field.NewUint(table, "material_definition_id")
	o.UseID = field.NewUint(table, "use_id")
	o.AssemblyTypeID = field.NewUint(table, "assembly_type_id")
	o.AssemblyRelationshipID = field.NewUint(table, "assembly_relationship_id")
	o.Quantity = field.NewString(table, "quantity")
	o.MeasurementID = field.NewUint(table, "measurement_id")

	o.fillFieldMap()

	return o
}

func (o *operationMaterialBillItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *operationMaterialBillItem) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 13)
	o.fieldMap["id"] = o.ID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["code"] = o.Code
	o.fieldMap["description"] = o.Description
	o.fieldMap["material_class_id"] = o.MaterialClassID
	o.fieldMap["material_definition_id"] = o.MaterialDefinitionID
	o.fieldMap["use_id"] = o.UseID
	o.fieldMap["assembly_type_id"] = o.AssemblyTypeID
	o.fieldMap["assembly_relationship_id"] = o.AssemblyRelationshipID
	o.fieldMap["quantity"] = o.Quantity
	o.fieldMap["measurement_id"] = o.MeasurementID
}

func (o operationMaterialBillItem) clone(db *gorm.DB) operationMaterialBillItem {
	o.operationMaterialBillItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o operationMaterialBillItem) replaceDB(db *gorm.DB) operationMaterialBillItem {
	o.operationMaterialBillItemDo.ReplaceDB(db)
	return o
}

type operationMaterialBillItemDo struct{ gen.DO }

func (o operationMaterialBillItemDo) Debug() *operationMaterialBillItemDo {
	return o.withDO(o.DO.Debug())
}

func (o operationMaterialBillItemDo) WithContext(ctx context.Context) *operationMaterialBillItemDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o operationMaterialBillItemDo) ReadDB() *operationMaterialBillItemDo {
	return o.Clauses(dbresolver.Read)
}

func (o operationMaterialBillItemDo) WriteDB() *operationMaterialBillItemDo {
	return o.Clauses(dbresolver.Write)
}

func (o operationMaterialBillItemDo) Session(config *gorm.Session) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Session(config))
}

func (o operationMaterialBillItemDo) Clauses(conds ...clause.Expression) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o operationMaterialBillItemDo) Returning(value interface{}, columns ...string) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o operationMaterialBillItemDo) Not(conds ...gen.Condition) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o operationMaterialBillItemDo) Or(conds ...gen.Condition) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o operationMaterialBillItemDo) Select(conds ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o operationMaterialBillItemDo) Where(conds ...gen.Condition) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o operationMaterialBillItemDo) Order(conds ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o operationMaterialBillItemDo) Distinct(cols ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o operationMaterialBillItemDo) Omit(cols ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o operationMaterialBillItemDo) Join(table schema.Tabler, on ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o operationMaterialBillItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o operationMaterialBillItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o operationMaterialBillItemDo) Group(cols ...field.Expr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o operationMaterialBillItemDo) Having(conds ...gen.Condition) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o operationMaterialBillItemDo) Limit(limit int) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o operationMaterialBillItemDo) Offset(offset int) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o operationMaterialBillItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o operationMaterialBillItemDo) Unscoped() *operationMaterialBillItemDo {
	return o.withDO(o.DO.Unscoped())
}

func (o operationMaterialBillItemDo) Create(values ...*isa95.OperationMaterialBillItem) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o operationMaterialBillItemDo) CreateInBatches(values []*isa95.OperationMaterialBillItem, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o operationMaterialBillItemDo) Save(values ...*isa95.OperationMaterialBillItem) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o operationMaterialBillItemDo) First() (*isa95.OperationMaterialBillItem, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.OperationMaterialBillItem), nil
	}
}

func (o operationMaterialBillItemDo) Take() (*isa95.OperationMaterialBillItem, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.OperationMaterialBillItem), nil
	}
}

func (o operationMaterialBillItemDo) Last() (*isa95.OperationMaterialBillItem, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.OperationMaterialBillItem), nil
	}
}

func (o operationMaterialBillItemDo) Find() ([]*isa95.OperationMaterialBillItem, error) {
	result, err := o.DO.Find()
	return result.([]*isa95.OperationMaterialBillItem), err
}

func (o operationMaterialBillItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.OperationMaterialBillItem, err error) {
	buf := make([]*isa95.OperationMaterialBillItem, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o operationMaterialBillItemDo) FindInBatches(result *[]*isa95.OperationMaterialBillItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o operationMaterialBillItemDo) Attrs(attrs ...field.AssignExpr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o operationMaterialBillItemDo) Assign(attrs ...field.AssignExpr) *operationMaterialBillItemDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o operationMaterialBillItemDo) Joins(fields ...field.RelationField) *operationMaterialBillItemDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o operationMaterialBillItemDo) Preload(fields ...field.RelationField) *operationMaterialBillItemDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o operationMaterialBillItemDo) FirstOrInit() (*isa95.OperationMaterialBillItem, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.OperationMaterialBillItem), nil
	}
}

func (o operationMaterialBillItemDo) FirstOrCreate() (*isa95.OperationMaterialBillItem, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.OperationMaterialBillItem), nil
	}
}

func (o operationMaterialBillItemDo) FindByPage(offset int, limit int) (result []*isa95.OperationMaterialBillItem, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o operationMaterialBillItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o operationMaterialBillItemDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o operationMaterialBillItemDo) Delete(models ...*isa95.OperationMaterialBillItem) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *operationMaterialBillItemDo) withDO(do gen.Dao) *operationMaterialBillItemDo {
	o.DO = *do.(*gen.DO)
	return o
}
