// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newPersonnelActual(db *gorm.DB, opts ...gen.DOOption) personnelActual {
	_personnelActual := personnelActual{}

	_personnelActual.personnelActualDo.UseDB(db, opts...)
	_personnelActual.personnelActualDo.UseModel(&isa95.PersonnelActual{})

	tableName := _personnelActual.personnelActualDo.TableName()
	_personnelActual.ALL = field.NewAsterisk(tableName)
	_personnelActual.ID = field.NewUint(tableName, "id")
	_personnelActual.CreatedAt = field.NewTime(tableName, "created_at")
	_personnelActual.UpdatedAt = field.NewTime(tableName, "updated_at")
	_personnelActual.DeletedAt = field.NewField(tableName, "deleted_at")
	_personnelActual.PersonnelClassID = field.NewUint(tableName, "personnel_class_id")
	_personnelActual.PersonID = field.NewUint(tableName, "person_id")
	_personnelActual.Description = field.NewString(tableName, "description")
	_personnelActual.UseID = field.NewUint(tableName, "use_id")
	_personnelActual.Quantity = field.NewString(tableName, "quantity")
	_personnelActual.MeasurementID = field.NewUint(tableName, "measurement_id")
	_personnelActual.Measurement = personnelActualBelongsToMeasurement{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Measurement", "isa95.Measurement"),
	}

	_personnelActual.fillFieldMap()

	return _personnelActual
}

type personnelActual struct {
	personnelActualDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	PersonnelClassID field.Uint
	PersonID         field.Uint
	Description      field.String
	UseID            field.Uint
	Quantity         field.String
	MeasurementID    field.Uint
	Measurement      personnelActualBelongsToMeasurement

	fieldMap map[string]field.Expr
}

func (p personnelActual) Table(newTableName string) *personnelActual {
	p.personnelActualDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personnelActual) As(alias string) *personnelActual {
	p.personnelActualDo.DO = *(p.personnelActualDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personnelActual) updateTableName(table string) *personnelActual {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PersonnelClassID = field.NewUint(table, "personnel_class_id")
	p.PersonID = field.NewUint(table, "person_id")
	p.Description = field.NewString(table, "description")
	p.UseID = field.NewUint(table, "use_id")
	p.Quantity = field.NewString(table, "quantity")
	p.MeasurementID = field.NewUint(table, "measurement_id")

	p.fillFieldMap()

	return p
}

func (p *personnelActual) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personnelActual) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["personnel_class_id"] = p.PersonnelClassID
	p.fieldMap["person_id"] = p.PersonID
	p.fieldMap["description"] = p.Description
	p.fieldMap["use_id"] = p.UseID
	p.fieldMap["quantity"] = p.Quantity
	p.fieldMap["measurement_id"] = p.MeasurementID

}

func (p personnelActual) clone(db *gorm.DB) personnelActual {
	p.personnelActualDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personnelActual) replaceDB(db *gorm.DB) personnelActual {
	p.personnelActualDo.ReplaceDB(db)
	return p
}

type personnelActualBelongsToMeasurement struct {
	db *gorm.DB

	field.RelationField
}

func (a personnelActualBelongsToMeasurement) Where(conds ...field.Expr) *personnelActualBelongsToMeasurement {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a personnelActualBelongsToMeasurement) WithContext(ctx context.Context) *personnelActualBelongsToMeasurement {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a personnelActualBelongsToMeasurement) Session(session *gorm.Session) *personnelActualBelongsToMeasurement {
	a.db = a.db.Session(session)
	return &a
}

func (a personnelActualBelongsToMeasurement) Model(m *isa95.PersonnelActual) *personnelActualBelongsToMeasurementTx {
	return &personnelActualBelongsToMeasurementTx{a.db.Model(m).Association(a.Name())}
}

type personnelActualBelongsToMeasurementTx struct{ tx *gorm.Association }

func (a personnelActualBelongsToMeasurementTx) Find() (result *isa95.Measurement, err error) {
	return result, a.tx.Find(&result)
}

func (a personnelActualBelongsToMeasurementTx) Append(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a personnelActualBelongsToMeasurementTx) Replace(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a personnelActualBelongsToMeasurementTx) Delete(values ...*isa95.Measurement) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a personnelActualBelongsToMeasurementTx) Clear() error {
	return a.tx.Clear()
}

func (a personnelActualBelongsToMeasurementTx) Count() int64 {
	return a.tx.Count()
}

type personnelActualDo struct{ gen.DO }

func (p personnelActualDo) Debug() *personnelActualDo {
	return p.withDO(p.DO.Debug())
}

func (p personnelActualDo) WithContext(ctx context.Context) *personnelActualDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personnelActualDo) ReadDB() *personnelActualDo {
	return p.Clauses(dbresolver.Read)
}

func (p personnelActualDo) WriteDB() *personnelActualDo {
	return p.Clauses(dbresolver.Write)
}

func (p personnelActualDo) Session(config *gorm.Session) *personnelActualDo {
	return p.withDO(p.DO.Session(config))
}

func (p personnelActualDo) Clauses(conds ...clause.Expression) *personnelActualDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personnelActualDo) Returning(value interface{}, columns ...string) *personnelActualDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personnelActualDo) Not(conds ...gen.Condition) *personnelActualDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personnelActualDo) Or(conds ...gen.Condition) *personnelActualDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personnelActualDo) Select(conds ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personnelActualDo) Where(conds ...gen.Condition) *personnelActualDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personnelActualDo) Order(conds ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personnelActualDo) Distinct(cols ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personnelActualDo) Omit(cols ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personnelActualDo) Join(table schema.Tabler, on ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personnelActualDo) LeftJoin(table schema.Tabler, on ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personnelActualDo) RightJoin(table schema.Tabler, on ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personnelActualDo) Group(cols ...field.Expr) *personnelActualDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personnelActualDo) Having(conds ...gen.Condition) *personnelActualDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personnelActualDo) Limit(limit int) *personnelActualDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personnelActualDo) Offset(offset int) *personnelActualDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personnelActualDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *personnelActualDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personnelActualDo) Unscoped() *personnelActualDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personnelActualDo) Create(values ...*isa95.PersonnelActual) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personnelActualDo) CreateInBatches(values []*isa95.PersonnelActual, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personnelActualDo) Save(values ...*isa95.PersonnelActual) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personnelActualDo) First() (*isa95.PersonnelActual, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelActual), nil
	}
}

func (p personnelActualDo) Take() (*isa95.PersonnelActual, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelActual), nil
	}
}

func (p personnelActualDo) Last() (*isa95.PersonnelActual, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelActual), nil
	}
}

func (p personnelActualDo) Find() ([]*isa95.PersonnelActual, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PersonnelActual), err
}

func (p personnelActualDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PersonnelActual, err error) {
	buf := make([]*isa95.PersonnelActual, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personnelActualDo) FindInBatches(result *[]*isa95.PersonnelActual, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personnelActualDo) Attrs(attrs ...field.AssignExpr) *personnelActualDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personnelActualDo) Assign(attrs ...field.AssignExpr) *personnelActualDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personnelActualDo) Joins(fields ...field.RelationField) *personnelActualDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personnelActualDo) Preload(fields ...field.RelationField) *personnelActualDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personnelActualDo) FirstOrInit() (*isa95.PersonnelActual, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelActual), nil
	}
}

func (p personnelActualDo) FirstOrCreate() (*isa95.PersonnelActual, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelActual), nil
	}
}

func (p personnelActualDo) FindByPage(offset int, limit int) (result []*isa95.PersonnelActual, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personnelActualDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personnelActualDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personnelActualDo) Delete(models ...*isa95.PersonnelActual) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personnelActualDo) withDO(do gen.Dao) *personnelActualDo {
	p.DO = *do.(*gen.DO)
	return p
}
