// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newPersonnelSegment(db *gorm.DB, opts ...gen.DOOption) personnelSegment {
	_personnelSegment := personnelSegment{}

	_personnelSegment.personnelSegmentDo.UseDB(db, opts...)
	_personnelSegment.personnelSegmentDo.UseModel(&isa95.PersonnelSegment{})

	tableName := _personnelSegment.personnelSegmentDo.TableName()
	_personnelSegment.ALL = field.NewAsterisk(tableName)
	_personnelSegment.ID = field.NewUint(tableName, "id")
	_personnelSegment.CreatedAt = field.NewTime(tableName, "created_at")
	_personnelSegment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_personnelSegment.DeletedAt = field.NewField(tableName, "deleted_at")
	_personnelSegment.PersonnelID = field.NewUint(tableName, "personnel_id")
	_personnelSegment.Description = field.NewString(tableName, "description")
	_personnelSegment.Quantity = field.NewString(tableName, "quantity")
	_personnelSegment.MeasurementID = field.NewUint(tableName, "measurement_id")
	_personnelSegment.UseID = field.NewUint(tableName, "use_id")

	_personnelSegment.fillFieldMap()

	return _personnelSegment
}

type personnelSegment struct {
	personnelSegmentDo

	ALL           field.Asterisk
	ID            field.Uint
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	PersonnelID   field.Uint
	Description   field.String
	Quantity      field.String
	MeasurementID field.Uint
	UseID         field.Uint

	fieldMap map[string]field.Expr
}

func (p personnelSegment) Table(newTableName string) *personnelSegment {
	p.personnelSegmentDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personnelSegment) As(alias string) *personnelSegment {
	p.personnelSegmentDo.DO = *(p.personnelSegmentDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personnelSegment) updateTableName(table string) *personnelSegment {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PersonnelID = field.NewUint(table, "personnel_id")
	p.Description = field.NewString(table, "description")
	p.Quantity = field.NewString(table, "quantity")
	p.MeasurementID = field.NewUint(table, "measurement_id")
	p.UseID = field.NewUint(table, "use_id")

	p.fillFieldMap()

	return p
}

func (p *personnelSegment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personnelSegment) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["personnel_id"] = p.PersonnelID
	p.fieldMap["description"] = p.Description
	p.fieldMap["quantity"] = p.Quantity
	p.fieldMap["measurement_id"] = p.MeasurementID
	p.fieldMap["use_id"] = p.UseID
}

func (p personnelSegment) clone(db *gorm.DB) personnelSegment {
	p.personnelSegmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personnelSegment) replaceDB(db *gorm.DB) personnelSegment {
	p.personnelSegmentDo.ReplaceDB(db)
	return p
}

type personnelSegmentDo struct{ gen.DO }

func (p personnelSegmentDo) Debug() *personnelSegmentDo {
	return p.withDO(p.DO.Debug())
}

func (p personnelSegmentDo) WithContext(ctx context.Context) *personnelSegmentDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personnelSegmentDo) ReadDB() *personnelSegmentDo {
	return p.Clauses(dbresolver.Read)
}

func (p personnelSegmentDo) WriteDB() *personnelSegmentDo {
	return p.Clauses(dbresolver.Write)
}

func (p personnelSegmentDo) Session(config *gorm.Session) *personnelSegmentDo {
	return p.withDO(p.DO.Session(config))
}

func (p personnelSegmentDo) Clauses(conds ...clause.Expression) *personnelSegmentDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personnelSegmentDo) Returning(value interface{}, columns ...string) *personnelSegmentDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personnelSegmentDo) Not(conds ...gen.Condition) *personnelSegmentDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personnelSegmentDo) Or(conds ...gen.Condition) *personnelSegmentDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personnelSegmentDo) Select(conds ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personnelSegmentDo) Where(conds ...gen.Condition) *personnelSegmentDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personnelSegmentDo) Order(conds ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personnelSegmentDo) Distinct(cols ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personnelSegmentDo) Omit(cols ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personnelSegmentDo) Join(table schema.Tabler, on ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personnelSegmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personnelSegmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personnelSegmentDo) Group(cols ...field.Expr) *personnelSegmentDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personnelSegmentDo) Having(conds ...gen.Condition) *personnelSegmentDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personnelSegmentDo) Limit(limit int) *personnelSegmentDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personnelSegmentDo) Offset(offset int) *personnelSegmentDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personnelSegmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *personnelSegmentDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personnelSegmentDo) Unscoped() *personnelSegmentDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personnelSegmentDo) Create(values ...*isa95.PersonnelSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personnelSegmentDo) CreateInBatches(values []*isa95.PersonnelSegment, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personnelSegmentDo) Save(values ...*isa95.PersonnelSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personnelSegmentDo) First() (*isa95.PersonnelSegment, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegment), nil
	}
}

func (p personnelSegmentDo) Take() (*isa95.PersonnelSegment, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegment), nil
	}
}

func (p personnelSegmentDo) Last() (*isa95.PersonnelSegment, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegment), nil
	}
}

func (p personnelSegmentDo) Find() ([]*isa95.PersonnelSegment, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PersonnelSegment), err
}

func (p personnelSegmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PersonnelSegment, err error) {
	buf := make([]*isa95.PersonnelSegment, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personnelSegmentDo) FindInBatches(result *[]*isa95.PersonnelSegment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personnelSegmentDo) Attrs(attrs ...field.AssignExpr) *personnelSegmentDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personnelSegmentDo) Assign(attrs ...field.AssignExpr) *personnelSegmentDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personnelSegmentDo) Joins(fields ...field.RelationField) *personnelSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personnelSegmentDo) Preload(fields ...field.RelationField) *personnelSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personnelSegmentDo) FirstOrInit() (*isa95.PersonnelSegment, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegment), nil
	}
}

func (p personnelSegmentDo) FirstOrCreate() (*isa95.PersonnelSegment, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegment), nil
	}
}

func (p personnelSegmentDo) FindByPage(offset int, limit int) (result []*isa95.PersonnelSegment, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personnelSegmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personnelSegmentDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personnelSegmentDo) Delete(models ...*isa95.PersonnelSegment) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personnelSegmentDo) withDO(do gen.Dao) *personnelSegmentDo {
	p.DO = *do.(*gen.DO)
	return p
}
