// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newPersonnelSegmentProp(db *gorm.DB, opts ...gen.DOOption) personnelSegmentProp {
	_personnelSegmentProp := personnelSegmentProp{}

	_personnelSegmentProp.personnelSegmentPropDo.UseDB(db, opts...)
	_personnelSegmentProp.personnelSegmentPropDo.UseModel(&isa95.PersonnelSegmentProp{})

	tableName := _personnelSegmentProp.personnelSegmentPropDo.TableName()
	_personnelSegmentProp.ALL = field.NewAsterisk(tableName)
	_personnelSegmentProp.ID = field.NewUint(tableName, "id")
	_personnelSegmentProp.CreatedAt = field.NewTime(tableName, "created_at")
	_personnelSegmentProp.UpdatedAt = field.NewTime(tableName, "updated_at")
	_personnelSegmentProp.DeletedAt = field.NewField(tableName, "deleted_at")
	_personnelSegmentProp.Code = field.NewString(tableName, "code")
	_personnelSegmentProp.Description = field.NewString(tableName, "description")
	_personnelSegmentProp.Value = field.NewString(tableName, "value")
	_personnelSegmentProp.ValueMeasurementID = field.NewUint(tableName, "value_measurement_id")
	_personnelSegmentProp.Quantity = field.NewString(tableName, "quantity")
	_personnelSegmentProp.QuantityMeasurementID = field.NewUint(tableName, "quantity_measurement_id")

	_personnelSegmentProp.fillFieldMap()

	return _personnelSegmentProp
}

type personnelSegmentProp struct {
	personnelSegmentPropDo

	ALL                   field.Asterisk
	ID                    field.Uint
	CreatedAt             field.Time
	UpdatedAt             field.Time
	DeletedAt             field.Field
	Code                  field.String
	Description           field.String
	Value                 field.String
	ValueMeasurementID    field.Uint
	Quantity              field.String
	QuantityMeasurementID field.Uint

	fieldMap map[string]field.Expr
}

func (p personnelSegmentProp) Table(newTableName string) *personnelSegmentProp {
	p.personnelSegmentPropDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personnelSegmentProp) As(alias string) *personnelSegmentProp {
	p.personnelSegmentPropDo.DO = *(p.personnelSegmentPropDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personnelSegmentProp) updateTableName(table string) *personnelSegmentProp {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Code = field.NewString(table, "code")
	p.Description = field.NewString(table, "description")
	p.Value = field.NewString(table, "value")
	p.ValueMeasurementID = field.NewUint(table, "value_measurement_id")
	p.Quantity = field.NewString(table, "quantity")
	p.QuantityMeasurementID = field.NewUint(table, "quantity_measurement_id")

	p.fillFieldMap()

	return p
}

func (p *personnelSegmentProp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personnelSegmentProp) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["code"] = p.Code
	p.fieldMap["description"] = p.Description
	p.fieldMap["value"] = p.Value
	p.fieldMap["value_measurement_id"] = p.ValueMeasurementID
	p.fieldMap["quantity"] = p.Quantity
	p.fieldMap["quantity_measurement_id"] = p.QuantityMeasurementID
}

func (p personnelSegmentProp) clone(db *gorm.DB) personnelSegmentProp {
	p.personnelSegmentPropDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personnelSegmentProp) replaceDB(db *gorm.DB) personnelSegmentProp {
	p.personnelSegmentPropDo.ReplaceDB(db)
	return p
}

type personnelSegmentPropDo struct{ gen.DO }

func (p personnelSegmentPropDo) Debug() *personnelSegmentPropDo {
	return p.withDO(p.DO.Debug())
}

func (p personnelSegmentPropDo) WithContext(ctx context.Context) *personnelSegmentPropDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personnelSegmentPropDo) ReadDB() *personnelSegmentPropDo {
	return p.Clauses(dbresolver.Read)
}

func (p personnelSegmentPropDo) WriteDB() *personnelSegmentPropDo {
	return p.Clauses(dbresolver.Write)
}

func (p personnelSegmentPropDo) Session(config *gorm.Session) *personnelSegmentPropDo {
	return p.withDO(p.DO.Session(config))
}

func (p personnelSegmentPropDo) Clauses(conds ...clause.Expression) *personnelSegmentPropDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personnelSegmentPropDo) Returning(value interface{}, columns ...string) *personnelSegmentPropDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personnelSegmentPropDo) Not(conds ...gen.Condition) *personnelSegmentPropDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personnelSegmentPropDo) Or(conds ...gen.Condition) *personnelSegmentPropDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personnelSegmentPropDo) Select(conds ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personnelSegmentPropDo) Where(conds ...gen.Condition) *personnelSegmentPropDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personnelSegmentPropDo) Order(conds ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personnelSegmentPropDo) Distinct(cols ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personnelSegmentPropDo) Omit(cols ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personnelSegmentPropDo) Join(table schema.Tabler, on ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personnelSegmentPropDo) LeftJoin(table schema.Tabler, on ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personnelSegmentPropDo) RightJoin(table schema.Tabler, on ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personnelSegmentPropDo) Group(cols ...field.Expr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personnelSegmentPropDo) Having(conds ...gen.Condition) *personnelSegmentPropDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personnelSegmentPropDo) Limit(limit int) *personnelSegmentPropDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personnelSegmentPropDo) Offset(offset int) *personnelSegmentPropDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personnelSegmentPropDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *personnelSegmentPropDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personnelSegmentPropDo) Unscoped() *personnelSegmentPropDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personnelSegmentPropDo) Create(values ...*isa95.PersonnelSegmentProp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personnelSegmentPropDo) CreateInBatches(values []*isa95.PersonnelSegmentProp, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personnelSegmentPropDo) Save(values ...*isa95.PersonnelSegmentProp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personnelSegmentPropDo) First() (*isa95.PersonnelSegmentProp, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegmentProp), nil
	}
}

func (p personnelSegmentPropDo) Take() (*isa95.PersonnelSegmentProp, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegmentProp), nil
	}
}

func (p personnelSegmentPropDo) Last() (*isa95.PersonnelSegmentProp, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegmentProp), nil
	}
}

func (p personnelSegmentPropDo) Find() ([]*isa95.PersonnelSegmentProp, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PersonnelSegmentProp), err
}

func (p personnelSegmentPropDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PersonnelSegmentProp, err error) {
	buf := make([]*isa95.PersonnelSegmentProp, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personnelSegmentPropDo) FindInBatches(result *[]*isa95.PersonnelSegmentProp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personnelSegmentPropDo) Attrs(attrs ...field.AssignExpr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personnelSegmentPropDo) Assign(attrs ...field.AssignExpr) *personnelSegmentPropDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personnelSegmentPropDo) Joins(fields ...field.RelationField) *personnelSegmentPropDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personnelSegmentPropDo) Preload(fields ...field.RelationField) *personnelSegmentPropDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personnelSegmentPropDo) FirstOrInit() (*isa95.PersonnelSegmentProp, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegmentProp), nil
	}
}

func (p personnelSegmentPropDo) FirstOrCreate() (*isa95.PersonnelSegmentProp, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelSegmentProp), nil
	}
}

func (p personnelSegmentPropDo) FindByPage(offset int, limit int) (result []*isa95.PersonnelSegmentProp, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personnelSegmentPropDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personnelSegmentPropDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personnelSegmentPropDo) Delete(models ...*isa95.PersonnelSegmentProp) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personnelSegmentPropDo) withDO(do gen.Dao) *personnelSegmentPropDo {
	p.DO = *do.(*gen.DO)
	return p
}
