// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newPhysicalAssetSegment(db *gorm.DB, opts ...gen.DOOption) physicalAssetSegment {
	_physicalAssetSegment := physicalAssetSegment{}

	_physicalAssetSegment.physicalAssetSegmentDo.UseDB(db, opts...)
	_physicalAssetSegment.physicalAssetSegmentDo.UseModel(&isa95.PhysicalAssetSegment{})

	tableName := _physicalAssetSegment.physicalAssetSegmentDo.TableName()
	_physicalAssetSegment.ALL = field.NewAsterisk(tableName)
	_physicalAssetSegment.ID = field.NewUint(tableName, "id")
	_physicalAssetSegment.CreatedAt = field.NewTime(tableName, "created_at")
	_physicalAssetSegment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_physicalAssetSegment.DeletedAt = field.NewField(tableName, "deleted_at")
	_physicalAssetSegment.PhysicalAssetClassID = field.NewUint(tableName, "physical_asset_class_id")
	_physicalAssetSegment.PhysicalAssetID = field.NewUint(tableName, "physical_asset_id")
	_physicalAssetSegment.Description = field.NewString(tableName, "description")
	_physicalAssetSegment.UseID = field.NewUint(tableName, "use_id")
	_physicalAssetSegment.Quantity = field.NewString(tableName, "quantity")
	_physicalAssetSegment.MeasurementID = field.NewUint(tableName, "measurement_id")

	_physicalAssetSegment.fillFieldMap()

	return _physicalAssetSegment
}

type physicalAssetSegment struct {
	physicalAssetSegmentDo

	ALL                  field.Asterisk
	ID                   field.Uint
	CreatedAt            field.Time
	UpdatedAt            field.Time
	DeletedAt            field.Field
	PhysicalAssetClassID field.Uint
	PhysicalAssetID      field.Uint
	Description          field.String
	UseID                field.Uint
	Quantity             field.String
	MeasurementID        field.Uint

	fieldMap map[string]field.Expr
}

func (p physicalAssetSegment) Table(newTableName string) *physicalAssetSegment {
	p.physicalAssetSegmentDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p physicalAssetSegment) As(alias string) *physicalAssetSegment {
	p.physicalAssetSegmentDo.DO = *(p.physicalAssetSegmentDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *physicalAssetSegment) updateTableName(table string) *physicalAssetSegment {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PhysicalAssetClassID = field.NewUint(table, "physical_asset_class_id")
	p.PhysicalAssetID = field.NewUint(table, "physical_asset_id")
	p.Description = field.NewString(table, "description")
	p.UseID = field.NewUint(table, "use_id")
	p.Quantity = field.NewString(table, "quantity")
	p.MeasurementID = field.NewUint(table, "measurement_id")

	p.fillFieldMap()

	return p
}

func (p *physicalAssetSegment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *physicalAssetSegment) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["physical_asset_class_id"] = p.PhysicalAssetClassID
	p.fieldMap["physical_asset_id"] = p.PhysicalAssetID
	p.fieldMap["description"] = p.Description
	p.fieldMap["use_id"] = p.UseID
	p.fieldMap["quantity"] = p.Quantity
	p.fieldMap["measurement_id"] = p.MeasurementID
}

func (p physicalAssetSegment) clone(db *gorm.DB) physicalAssetSegment {
	p.physicalAssetSegmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p physicalAssetSegment) replaceDB(db *gorm.DB) physicalAssetSegment {
	p.physicalAssetSegmentDo.ReplaceDB(db)
	return p
}

type physicalAssetSegmentDo struct{ gen.DO }

func (p physicalAssetSegmentDo) Debug() *physicalAssetSegmentDo {
	return p.withDO(p.DO.Debug())
}

func (p physicalAssetSegmentDo) WithContext(ctx context.Context) *physicalAssetSegmentDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p physicalAssetSegmentDo) ReadDB() *physicalAssetSegmentDo {
	return p.Clauses(dbresolver.Read)
}

func (p physicalAssetSegmentDo) WriteDB() *physicalAssetSegmentDo {
	return p.Clauses(dbresolver.Write)
}

func (p physicalAssetSegmentDo) Session(config *gorm.Session) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Session(config))
}

func (p physicalAssetSegmentDo) Clauses(conds ...clause.Expression) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p physicalAssetSegmentDo) Returning(value interface{}, columns ...string) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p physicalAssetSegmentDo) Not(conds ...gen.Condition) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p physicalAssetSegmentDo) Or(conds ...gen.Condition) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p physicalAssetSegmentDo) Select(conds ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p physicalAssetSegmentDo) Where(conds ...gen.Condition) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p physicalAssetSegmentDo) Order(conds ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p physicalAssetSegmentDo) Distinct(cols ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p physicalAssetSegmentDo) Omit(cols ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p physicalAssetSegmentDo) Join(table schema.Tabler, on ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p physicalAssetSegmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p physicalAssetSegmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p physicalAssetSegmentDo) Group(cols ...field.Expr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p physicalAssetSegmentDo) Having(conds ...gen.Condition) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p physicalAssetSegmentDo) Limit(limit int) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p physicalAssetSegmentDo) Offset(offset int) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p physicalAssetSegmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p physicalAssetSegmentDo) Unscoped() *physicalAssetSegmentDo {
	return p.withDO(p.DO.Unscoped())
}

func (p physicalAssetSegmentDo) Create(values ...*isa95.PhysicalAssetSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p physicalAssetSegmentDo) CreateInBatches(values []*isa95.PhysicalAssetSegment, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p physicalAssetSegmentDo) Save(values ...*isa95.PhysicalAssetSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p physicalAssetSegmentDo) First() (*isa95.PhysicalAssetSegment, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PhysicalAssetSegment), nil
	}
}

func (p physicalAssetSegmentDo) Take() (*isa95.PhysicalAssetSegment, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PhysicalAssetSegment), nil
	}
}

func (p physicalAssetSegmentDo) Last() (*isa95.PhysicalAssetSegment, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PhysicalAssetSegment), nil
	}
}

func (p physicalAssetSegmentDo) Find() ([]*isa95.PhysicalAssetSegment, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PhysicalAssetSegment), err
}

func (p physicalAssetSegmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PhysicalAssetSegment, err error) {
	buf := make([]*isa95.PhysicalAssetSegment, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p physicalAssetSegmentDo) FindInBatches(result *[]*isa95.PhysicalAssetSegment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p physicalAssetSegmentDo) Attrs(attrs ...field.AssignExpr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p physicalAssetSegmentDo) Assign(attrs ...field.AssignExpr) *physicalAssetSegmentDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p physicalAssetSegmentDo) Joins(fields ...field.RelationField) *physicalAssetSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p physicalAssetSegmentDo) Preload(fields ...field.RelationField) *physicalAssetSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p physicalAssetSegmentDo) FirstOrInit() (*isa95.PhysicalAssetSegment, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PhysicalAssetSegment), nil
	}
}

func (p physicalAssetSegmentDo) FirstOrCreate() (*isa95.PhysicalAssetSegment, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PhysicalAssetSegment), nil
	}
}

func (p physicalAssetSegmentDo) FindByPage(offset int, limit int) (result []*isa95.PhysicalAssetSegment, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p physicalAssetSegmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p physicalAssetSegmentDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p physicalAssetSegmentDo) Delete(models ...*isa95.PhysicalAssetSegment) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *physicalAssetSegmentDo) withDO(do gen.Dao) *physicalAssetSegmentDo {
	p.DO = *do.(*gen.DO)
	return p
}
