// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newProcessSegment(db *gorm.DB, opts ...gen.DOOption) processSegment {
	_processSegment := processSegment{}

	_processSegment.processSegmentDo.UseDB(db, opts...)
	_processSegment.processSegmentDo.UseModel(&isa95.ProcessSegment{})

	tableName := _processSegment.processSegmentDo.TableName()
	_processSegment.ALL = field.NewAsterisk(tableName)
	_processSegment.ID = field.NewUint(tableName, "id")
	_processSegment.CreatedAt = field.NewTime(tableName, "created_at")
	_processSegment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_processSegment.DeletedAt = field.NewField(tableName, "deleted_at")
	_processSegment.Code = field.NewUint(tableName, "code")
	_processSegment.Description = field.NewString(tableName, "description")
	_processSegment.OperationTypeID = field.NewUint(tableName, "operation_type_id")
	_processSegment.LevelID = field.NewUint(tableName, "level_id")
	_processSegment.Duration = field.NewString(tableName, "duration")
	_processSegment.MeasurementID = field.NewUint(tableName, "measurement_id")

	_processSegment.fillFieldMap()

	return _processSegment
}

type processSegment struct {
	processSegmentDo

	ALL             field.Asterisk
	ID              field.Uint
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	Code            field.Uint
	Description     field.String
	OperationTypeID field.Uint
	LevelID         field.Uint
	Duration        field.String
	MeasurementID   field.Uint

	fieldMap map[string]field.Expr
}

func (p processSegment) Table(newTableName string) *processSegment {
	p.processSegmentDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processSegment) As(alias string) *processSegment {
	p.processSegmentDo.DO = *(p.processSegmentDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processSegment) updateTableName(table string) *processSegment {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Code = field.NewUint(table, "code")
	p.Description = field.NewString(table, "description")
	p.OperationTypeID = field.NewUint(table, "operation_type_id")
	p.LevelID = field.NewUint(table, "level_id")
	p.Duration = field.NewString(table, "duration")
	p.MeasurementID = field.NewUint(table, "measurement_id")

	p.fillFieldMap()

	return p
}

func (p *processSegment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processSegment) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["code"] = p.Code
	p.fieldMap["description"] = p.Description
	p.fieldMap["operation_type_id"] = p.OperationTypeID
	p.fieldMap["level_id"] = p.LevelID
	p.fieldMap["duration"] = p.Duration
	p.fieldMap["measurement_id"] = p.MeasurementID
}

func (p processSegment) clone(db *gorm.DB) processSegment {
	p.processSegmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processSegment) replaceDB(db *gorm.DB) processSegment {
	p.processSegmentDo.ReplaceDB(db)
	return p
}

type processSegmentDo struct{ gen.DO }

func (p processSegmentDo) Debug() *processSegmentDo {
	return p.withDO(p.DO.Debug())
}

func (p processSegmentDo) WithContext(ctx context.Context) *processSegmentDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processSegmentDo) ReadDB() *processSegmentDo {
	return p.Clauses(dbresolver.Read)
}

func (p processSegmentDo) WriteDB() *processSegmentDo {
	return p.Clauses(dbresolver.Write)
}

func (p processSegmentDo) Session(config *gorm.Session) *processSegmentDo {
	return p.withDO(p.DO.Session(config))
}

func (p processSegmentDo) Clauses(conds ...clause.Expression) *processSegmentDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processSegmentDo) Returning(value interface{}, columns ...string) *processSegmentDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processSegmentDo) Not(conds ...gen.Condition) *processSegmentDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processSegmentDo) Or(conds ...gen.Condition) *processSegmentDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processSegmentDo) Select(conds ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processSegmentDo) Where(conds ...gen.Condition) *processSegmentDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processSegmentDo) Order(conds ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processSegmentDo) Distinct(cols ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processSegmentDo) Omit(cols ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processSegmentDo) Join(table schema.Tabler, on ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processSegmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processSegmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processSegmentDo) Group(cols ...field.Expr) *processSegmentDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processSegmentDo) Having(conds ...gen.Condition) *processSegmentDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processSegmentDo) Limit(limit int) *processSegmentDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processSegmentDo) Offset(offset int) *processSegmentDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processSegmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *processSegmentDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processSegmentDo) Unscoped() *processSegmentDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processSegmentDo) Create(values ...*isa95.ProcessSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processSegmentDo) CreateInBatches(values []*isa95.ProcessSegment, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processSegmentDo) Save(values ...*isa95.ProcessSegment) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processSegmentDo) First() (*isa95.ProcessSegment, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegment), nil
	}
}

func (p processSegmentDo) Take() (*isa95.ProcessSegment, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegment), nil
	}
}

func (p processSegmentDo) Last() (*isa95.ProcessSegment, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegment), nil
	}
}

func (p processSegmentDo) Find() ([]*isa95.ProcessSegment, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.ProcessSegment), err
}

func (p processSegmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.ProcessSegment, err error) {
	buf := make([]*isa95.ProcessSegment, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processSegmentDo) FindInBatches(result *[]*isa95.ProcessSegment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processSegmentDo) Attrs(attrs ...field.AssignExpr) *processSegmentDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processSegmentDo) Assign(attrs ...field.AssignExpr) *processSegmentDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processSegmentDo) Joins(fields ...field.RelationField) *processSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processSegmentDo) Preload(fields ...field.RelationField) *processSegmentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processSegmentDo) FirstOrInit() (*isa95.ProcessSegment, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegment), nil
	}
}

func (p processSegmentDo) FirstOrCreate() (*isa95.ProcessSegment, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegment), nil
	}
}

func (p processSegmentDo) FindByPage(offset int, limit int) (result []*isa95.ProcessSegment, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processSegmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processSegmentDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processSegmentDo) Delete(models ...*isa95.ProcessSegment) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processSegmentDo) withDO(do gen.Dao) *processSegmentDo {
	p.DO = *do.(*gen.DO)
	return p
}
