// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newProcessSegmentParameter(db *gorm.DB, opts ...gen.DOOption) processSegmentParameter {
	_processSegmentParameter := processSegmentParameter{}

	_processSegmentParameter.processSegmentParameterDo.UseDB(db, opts...)
	_processSegmentParameter.processSegmentParameterDo.UseModel(&isa95.ProcessSegmentParameter{})

	tableName := _processSegmentParameter.processSegmentParameterDo.TableName()
	_processSegmentParameter.ALL = field.NewAsterisk(tableName)
	_processSegmentParameter.ID = field.NewUint(tableName, "id")
	_processSegmentParameter.CreatedAt = field.NewTime(tableName, "created_at")
	_processSegmentParameter.UpdatedAt = field.NewTime(tableName, "updated_at")
	_processSegmentParameter.DeletedAt = field.NewField(tableName, "deleted_at")
	_processSegmentParameter.Description = field.NewString(tableName, "description")
	_processSegmentParameter.Value = field.NewString(tableName, "value")
	_processSegmentParameter.MeasurementID = field.NewUint(tableName, "measurement_id")

	_processSegmentParameter.fillFieldMap()

	return _processSegmentParameter
}

type processSegmentParameter struct {
	processSegmentParameterDo

	ALL           field.Asterisk
	ID            field.Uint
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	Description   field.String
	Value         field.String
	MeasurementID field.Uint

	fieldMap map[string]field.Expr
}

func (p processSegmentParameter) Table(newTableName string) *processSegmentParameter {
	p.processSegmentParameterDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processSegmentParameter) As(alias string) *processSegmentParameter {
	p.processSegmentParameterDo.DO = *(p.processSegmentParameterDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processSegmentParameter) updateTableName(table string) *processSegmentParameter {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Description = field.NewString(table, "description")
	p.Value = field.NewString(table, "value")
	p.MeasurementID = field.NewUint(table, "measurement_id")

	p.fillFieldMap()

	return p
}

func (p *processSegmentParameter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processSegmentParameter) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["description"] = p.Description
	p.fieldMap["value"] = p.Value
	p.fieldMap["measurement_id"] = p.MeasurementID
}

func (p processSegmentParameter) clone(db *gorm.DB) processSegmentParameter {
	p.processSegmentParameterDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processSegmentParameter) replaceDB(db *gorm.DB) processSegmentParameter {
	p.processSegmentParameterDo.ReplaceDB(db)
	return p
}

type processSegmentParameterDo struct{ gen.DO }

func (p processSegmentParameterDo) Debug() *processSegmentParameterDo {
	return p.withDO(p.DO.Debug())
}

func (p processSegmentParameterDo) WithContext(ctx context.Context) *processSegmentParameterDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processSegmentParameterDo) ReadDB() *processSegmentParameterDo {
	return p.Clauses(dbresolver.Read)
}

func (p processSegmentParameterDo) WriteDB() *processSegmentParameterDo {
	return p.Clauses(dbresolver.Write)
}

func (p processSegmentParameterDo) Session(config *gorm.Session) *processSegmentParameterDo {
	return p.withDO(p.DO.Session(config))
}

func (p processSegmentParameterDo) Clauses(conds ...clause.Expression) *processSegmentParameterDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processSegmentParameterDo) Returning(value interface{}, columns ...string) *processSegmentParameterDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processSegmentParameterDo) Not(conds ...gen.Condition) *processSegmentParameterDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processSegmentParameterDo) Or(conds ...gen.Condition) *processSegmentParameterDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processSegmentParameterDo) Select(conds ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processSegmentParameterDo) Where(conds ...gen.Condition) *processSegmentParameterDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processSegmentParameterDo) Order(conds ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processSegmentParameterDo) Distinct(cols ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processSegmentParameterDo) Omit(cols ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processSegmentParameterDo) Join(table schema.Tabler, on ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processSegmentParameterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processSegmentParameterDo) RightJoin(table schema.Tabler, on ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processSegmentParameterDo) Group(cols ...field.Expr) *processSegmentParameterDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processSegmentParameterDo) Having(conds ...gen.Condition) *processSegmentParameterDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processSegmentParameterDo) Limit(limit int) *processSegmentParameterDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processSegmentParameterDo) Offset(offset int) *processSegmentParameterDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processSegmentParameterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *processSegmentParameterDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processSegmentParameterDo) Unscoped() *processSegmentParameterDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processSegmentParameterDo) Create(values ...*isa95.ProcessSegmentParameter) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processSegmentParameterDo) CreateInBatches(values []*isa95.ProcessSegmentParameter, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processSegmentParameterDo) Save(values ...*isa95.ProcessSegmentParameter) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processSegmentParameterDo) First() (*isa95.ProcessSegmentParameter, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentParameter), nil
	}
}

func (p processSegmentParameterDo) Take() (*isa95.ProcessSegmentParameter, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentParameter), nil
	}
}

func (p processSegmentParameterDo) Last() (*isa95.ProcessSegmentParameter, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentParameter), nil
	}
}

func (p processSegmentParameterDo) Find() ([]*isa95.ProcessSegmentParameter, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.ProcessSegmentParameter), err
}

func (p processSegmentParameterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.ProcessSegmentParameter, err error) {
	buf := make([]*isa95.ProcessSegmentParameter, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processSegmentParameterDo) FindInBatches(result *[]*isa95.ProcessSegmentParameter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processSegmentParameterDo) Attrs(attrs ...field.AssignExpr) *processSegmentParameterDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processSegmentParameterDo) Assign(attrs ...field.AssignExpr) *processSegmentParameterDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processSegmentParameterDo) Joins(fields ...field.RelationField) *processSegmentParameterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processSegmentParameterDo) Preload(fields ...field.RelationField) *processSegmentParameterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processSegmentParameterDo) FirstOrInit() (*isa95.ProcessSegmentParameter, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentParameter), nil
	}
}

func (p processSegmentParameterDo) FirstOrCreate() (*isa95.ProcessSegmentParameter, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentParameter), nil
	}
}

func (p processSegmentParameterDo) FindByPage(offset int, limit int) (result []*isa95.ProcessSegmentParameter, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processSegmentParameterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processSegmentParameterDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processSegmentParameterDo) Delete(models ...*isa95.ProcessSegmentParameter) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processSegmentParameterDo) withDO(do gen.Dao) *processSegmentParameterDo {
	p.DO = *do.(*gen.DO)
	return p
}
