// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/server/internal/model/isa95"
)

func newProcessSegmentCapability(db *gorm.DB, opts ...gen.DOOption) processSegmentCapability {
	_processSegmentCapability := processSegmentCapability{}

	_processSegmentCapability.processSegmentCapabilityDo.UseDB(db, opts...)
	_processSegmentCapability.processSegmentCapabilityDo.UseModel(&isa95.ProcessSegmentCapability{})

	tableName := _processSegmentCapability.processSegmentCapabilityDo.TableName()
	_processSegmentCapability.ALL = field.NewAsterisk(tableName)
	_processSegmentCapability.ID = field.NewUint(tableName, "id")
	_processSegmentCapability.CreatedAt = field.NewTime(tableName, "created_at")
	_processSegmentCapability.UpdatedAt = field.NewTime(tableName, "updated_at")
	_processSegmentCapability.DeletedAt = field.NewField(tableName, "deleted_at")
	_processSegmentCapability.Code = field.NewString(tableName, "code")
	_processSegmentCapability.Description = field.NewString(tableName, "description")
	_processSegmentCapability.ProcessSegmentID = field.NewUint(tableName, "process_segment_id")
	_processSegmentCapability.CapacityType = field.NewString(tableName, "capacity_type")
	_processSegmentCapability.Reason = field.NewString(tableName, "reason")
	_processSegmentCapability.LevelID = field.NewUint(tableName, "level_id")
	_processSegmentCapability.StartTime = field.NewTime(tableName, "start_time")
	_processSegmentCapability.EndTime = field.NewTime(tableName, "end_time")

	_processSegmentCapability.fillFieldMap()

	return _processSegmentCapability
}

type processSegmentCapability struct {
	processSegmentCapabilityDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	Code             field.String
	Description      field.String
	ProcessSegmentID field.Uint
	CapacityType     field.String
	Reason           field.String
	LevelID          field.Uint
	StartTime        field.Time
	EndTime          field.Time

	fieldMap map[string]field.Expr
}

func (p processSegmentCapability) Table(newTableName string) *processSegmentCapability {
	p.processSegmentCapabilityDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processSegmentCapability) As(alias string) *processSegmentCapability {
	p.processSegmentCapabilityDo.DO = *(p.processSegmentCapabilityDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processSegmentCapability) updateTableName(table string) *processSegmentCapability {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Code = field.NewString(table, "code")
	p.Description = field.NewString(table, "description")
	p.ProcessSegmentID = field.NewUint(table, "process_segment_id")
	p.CapacityType = field.NewString(table, "capacity_type")
	p.Reason = field.NewString(table, "reason")
	p.LevelID = field.NewUint(table, "level_id")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")

	p.fillFieldMap()

	return p
}

func (p *processSegmentCapability) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processSegmentCapability) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["code"] = p.Code
	p.fieldMap["description"] = p.Description
	p.fieldMap["process_segment_id"] = p.ProcessSegmentID
	p.fieldMap["capacity_type"] = p.CapacityType
	p.fieldMap["reason"] = p.Reason
	p.fieldMap["level_id"] = p.LevelID
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
}

func (p processSegmentCapability) clone(db *gorm.DB) processSegmentCapability {
	p.processSegmentCapabilityDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processSegmentCapability) replaceDB(db *gorm.DB) processSegmentCapability {
	p.processSegmentCapabilityDo.ReplaceDB(db)
	return p
}

type processSegmentCapabilityDo struct{ gen.DO }

func (p processSegmentCapabilityDo) Debug() *processSegmentCapabilityDo {
	return p.withDO(p.DO.Debug())
}

func (p processSegmentCapabilityDo) WithContext(ctx context.Context) *processSegmentCapabilityDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processSegmentCapabilityDo) ReadDB() *processSegmentCapabilityDo {
	return p.Clauses(dbresolver.Read)
}

func (p processSegmentCapabilityDo) WriteDB() *processSegmentCapabilityDo {
	return p.Clauses(dbresolver.Write)
}

func (p processSegmentCapabilityDo) Session(config *gorm.Session) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Session(config))
}

func (p processSegmentCapabilityDo) Clauses(conds ...clause.Expression) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processSegmentCapabilityDo) Returning(value interface{}, columns ...string) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processSegmentCapabilityDo) Not(conds ...gen.Condition) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processSegmentCapabilityDo) Or(conds ...gen.Condition) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processSegmentCapabilityDo) Select(conds ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processSegmentCapabilityDo) Where(conds ...gen.Condition) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processSegmentCapabilityDo) Order(conds ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processSegmentCapabilityDo) Distinct(cols ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processSegmentCapabilityDo) Omit(cols ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processSegmentCapabilityDo) Join(table schema.Tabler, on ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processSegmentCapabilityDo) LeftJoin(table schema.Tabler, on ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processSegmentCapabilityDo) RightJoin(table schema.Tabler, on ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processSegmentCapabilityDo) Group(cols ...field.Expr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processSegmentCapabilityDo) Having(conds ...gen.Condition) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processSegmentCapabilityDo) Limit(limit int) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processSegmentCapabilityDo) Offset(offset int) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processSegmentCapabilityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processSegmentCapabilityDo) Unscoped() *processSegmentCapabilityDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processSegmentCapabilityDo) Create(values ...*isa95.ProcessSegmentCapability) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processSegmentCapabilityDo) CreateInBatches(values []*isa95.ProcessSegmentCapability, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processSegmentCapabilityDo) Save(values ...*isa95.ProcessSegmentCapability) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processSegmentCapabilityDo) First() (*isa95.ProcessSegmentCapability, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentCapability), nil
	}
}

func (p processSegmentCapabilityDo) Take() (*isa95.ProcessSegmentCapability, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentCapability), nil
	}
}

func (p processSegmentCapabilityDo) Last() (*isa95.ProcessSegmentCapability, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentCapability), nil
	}
}

func (p processSegmentCapabilityDo) Find() ([]*isa95.ProcessSegmentCapability, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.ProcessSegmentCapability), err
}

func (p processSegmentCapabilityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.ProcessSegmentCapability, err error) {
	buf := make([]*isa95.ProcessSegmentCapability, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processSegmentCapabilityDo) FindInBatches(result *[]*isa95.ProcessSegmentCapability, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processSegmentCapabilityDo) Attrs(attrs ...field.AssignExpr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processSegmentCapabilityDo) Assign(attrs ...field.AssignExpr) *processSegmentCapabilityDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processSegmentCapabilityDo) Joins(fields ...field.RelationField) *processSegmentCapabilityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processSegmentCapabilityDo) Preload(fields ...field.RelationField) *processSegmentCapabilityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processSegmentCapabilityDo) FirstOrInit() (*isa95.ProcessSegmentCapability, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentCapability), nil
	}
}

func (p processSegmentCapabilityDo) FirstOrCreate() (*isa95.ProcessSegmentCapability, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.ProcessSegmentCapability), nil
	}
}

func (p processSegmentCapabilityDo) FindByPage(offset int, limit int) (result []*isa95.ProcessSegmentCapability, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processSegmentCapabilityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processSegmentCapabilityDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processSegmentCapabilityDo) Delete(models ...*isa95.ProcessSegmentCapability) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processSegmentCapabilityDo) withDO(do gen.Dao) *processSegmentCapabilityDo {
	p.DO = *do.(*gen.DO)
	return p
}
