[build]
pre_cmd = ["swag init -g ./server/server.go -o ./server/internal/api/docs -q && swag fmt"]
cmd = "go build -o ./cmd/tmp/main ./cmd/gomes/main.go"
exclude_dir = ["server/internal/api/docs", "server/internal/dao", "cmd/tmp", "server/internal/model/gen"]
bin = "./cmd/tmp/main"