externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    name: Noah Burnette
    url: https://github.com/nburnet1/gomes/issues
  description: Describes endpoints used by GoMES.
  license:
    name: MIT
    url: https://github.com/nburnet1/gomes/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: GoMES API
  version: "0.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
