// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/pkg/model/isa95"
)

func newPersonProp(db *gorm.DB, opts ...gen.DOOption) personProp {
	_personProp := personProp{}

	_personProp.personPropDo.UseDB(db, opts...)
	_personProp.personPropDo.UseModel(&isa95.PersonProp{})

	tableName := _personProp.personPropDo.TableName()
	_personProp.ALL = field.NewAsterisk(tableName)
	_personProp.ID = field.NewUint(tableName, "id")
	_personProp.CreatedAt = field.NewTime(tableName, "created_at")
	_personProp.UpdatedAt = field.NewTime(tableName, "updated_at")
	_personProp.DeletedAt = field.NewField(tableName, "deleted_at")
	_personProp.PersonID = field.NewUint(tableName, "person_id")
	_personProp.Description = field.NewString(tableName, "description")
	_personProp.Value = field.NewString(tableName, "value")
	_personProp.MeasurementID = field.NewUint(tableName, "measurement_id")
	_personProp.Person = personPropBelongsToPerson{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Person", "isa95.Person"),
		PersonnelClass: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Person.PersonnelClass", "isa95.PersonnelClass"),
		},
	}

	_personProp.fillFieldMap()

	return _personProp
}

type personProp struct {
	personPropDo

	ALL           field.Asterisk
	ID            field.Uint
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	PersonID      field.Uint
	Description   field.String
	Value         field.String
	MeasurementID field.Uint
	Person        personPropBelongsToPerson

	fieldMap map[string]field.Expr
}

func (p personProp) Table(newTableName string) *personProp {
	p.personPropDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personProp) As(alias string) *personProp {
	p.personPropDo.DO = *(p.personPropDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personProp) updateTableName(table string) *personProp {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PersonID = field.NewUint(table, "person_id")
	p.Description = field.NewString(table, "description")
	p.Value = field.NewString(table, "value")
	p.MeasurementID = field.NewUint(table, "measurement_id")

	p.fillFieldMap()

	return p
}

func (p *personProp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personProp) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["person_id"] = p.PersonID
	p.fieldMap["description"] = p.Description
	p.fieldMap["value"] = p.Value
	p.fieldMap["measurement_id"] = p.MeasurementID

}

func (p personProp) clone(db *gorm.DB) personProp {
	p.personPropDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personProp) replaceDB(db *gorm.DB) personProp {
	p.personPropDo.ReplaceDB(db)
	return p
}

type personPropBelongsToPerson struct {
	db *gorm.DB

	field.RelationField

	PersonnelClass struct {
		field.RelationField
	}
}

func (a personPropBelongsToPerson) Where(conds ...field.Expr) *personPropBelongsToPerson {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a personPropBelongsToPerson) WithContext(ctx context.Context) *personPropBelongsToPerson {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a personPropBelongsToPerson) Session(session *gorm.Session) *personPropBelongsToPerson {
	a.db = a.db.Session(session)
	return &a
}

func (a personPropBelongsToPerson) Model(m *isa95.PersonProp) *personPropBelongsToPersonTx {
	return &personPropBelongsToPersonTx{a.db.Model(m).Association(a.Name())}
}

type personPropBelongsToPersonTx struct{ tx *gorm.Association }

func (a personPropBelongsToPersonTx) Find() (result *isa95.Person, err error) {
	return result, a.tx.Find(&result)
}

func (a personPropBelongsToPersonTx) Append(values ...*isa95.Person) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a personPropBelongsToPersonTx) Replace(values ...*isa95.Person) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a personPropBelongsToPersonTx) Delete(values ...*isa95.Person) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a personPropBelongsToPersonTx) Clear() error {
	return a.tx.Clear()
}

func (a personPropBelongsToPersonTx) Count() int64 {
	return a.tx.Count()
}

type personPropDo struct{ gen.DO }

func (p personPropDo) Debug() *personPropDo {
	return p.withDO(p.DO.Debug())
}

func (p personPropDo) WithContext(ctx context.Context) *personPropDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personPropDo) ReadDB() *personPropDo {
	return p.Clauses(dbresolver.Read)
}

func (p personPropDo) WriteDB() *personPropDo {
	return p.Clauses(dbresolver.Write)
}

func (p personPropDo) Session(config *gorm.Session) *personPropDo {
	return p.withDO(p.DO.Session(config))
}

func (p personPropDo) Clauses(conds ...clause.Expression) *personPropDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personPropDo) Returning(value interface{}, columns ...string) *personPropDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personPropDo) Not(conds ...gen.Condition) *personPropDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personPropDo) Or(conds ...gen.Condition) *personPropDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personPropDo) Select(conds ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personPropDo) Where(conds ...gen.Condition) *personPropDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personPropDo) Order(conds ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personPropDo) Distinct(cols ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personPropDo) Omit(cols ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personPropDo) Join(table schema.Tabler, on ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personPropDo) LeftJoin(table schema.Tabler, on ...field.Expr) *personPropDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personPropDo) RightJoin(table schema.Tabler, on ...field.Expr) *personPropDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personPropDo) Group(cols ...field.Expr) *personPropDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personPropDo) Having(conds ...gen.Condition) *personPropDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personPropDo) Limit(limit int) *personPropDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personPropDo) Offset(offset int) *personPropDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personPropDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *personPropDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personPropDo) Unscoped() *personPropDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personPropDo) Create(values ...*isa95.PersonProp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personPropDo) CreateInBatches(values []*isa95.PersonProp, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personPropDo) Save(values ...*isa95.PersonProp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personPropDo) First() (*isa95.PersonProp, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonProp), nil
	}
}

func (p personPropDo) Take() (*isa95.PersonProp, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonProp), nil
	}
}

func (p personPropDo) Last() (*isa95.PersonProp, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonProp), nil
	}
}

func (p personPropDo) Find() ([]*isa95.PersonProp, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PersonProp), err
}

func (p personPropDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PersonProp, err error) {
	buf := make([]*isa95.PersonProp, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personPropDo) FindInBatches(result *[]*isa95.PersonProp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personPropDo) Attrs(attrs ...field.AssignExpr) *personPropDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personPropDo) Assign(attrs ...field.AssignExpr) *personPropDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personPropDo) Joins(fields ...field.RelationField) *personPropDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personPropDo) Preload(fields ...field.RelationField) *personPropDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personPropDo) FirstOrInit() (*isa95.PersonProp, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonProp), nil
	}
}

func (p personPropDo) FirstOrCreate() (*isa95.PersonProp, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonProp), nil
	}
}

func (p personPropDo) FindByPage(offset int, limit int) (result []*isa95.PersonProp, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personPropDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personPropDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personPropDo) Delete(models ...*isa95.PersonProp) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personPropDo) withDO(do gen.Dao) *personPropDo {
	p.DO = *do.(*gen.DO)
	return p
}
