// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package isa95

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gomes/pkg/model/isa95"
)

func newPersonnelClass(db *gorm.DB, opts ...gen.DOOption) personnelClass {
	_personnelClass := personnelClass{}

	_personnelClass.personnelClassDo.UseDB(db, opts...)
	_personnelClass.personnelClassDo.UseModel(&isa95.PersonnelClass{})

	tableName := _personnelClass.personnelClassDo.TableName()
	_personnelClass.ALL = field.NewAsterisk(tableName)
	_personnelClass.ID = field.NewUint(tableName, "id")
	_personnelClass.CreatedAt = field.NewTime(tableName, "created_at")
	_personnelClass.UpdatedAt = field.NewTime(tableName, "updated_at")
	_personnelClass.DeletedAt = field.NewField(tableName, "deleted_at")
	_personnelClass.Code = field.NewString(tableName, "code")
	_personnelClass.Description = field.NewString(tableName, "description")

	_personnelClass.fillFieldMap()

	return _personnelClass
}

type personnelClass struct {
	personnelClassDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Code        field.String
	Description field.String

	fieldMap map[string]field.Expr
}

func (p personnelClass) Table(newTableName string) *personnelClass {
	p.personnelClassDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personnelClass) As(alias string) *personnelClass {
	p.personnelClassDo.DO = *(p.personnelClassDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personnelClass) updateTableName(table string) *personnelClass {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Code = field.NewString(table, "code")
	p.Description = field.NewString(table, "description")

	p.fillFieldMap()

	return p
}

func (p *personnelClass) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personnelClass) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["code"] = p.Code
	p.fieldMap["description"] = p.Description
}

func (p personnelClass) clone(db *gorm.DB) personnelClass {
	p.personnelClassDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personnelClass) replaceDB(db *gorm.DB) personnelClass {
	p.personnelClassDo.ReplaceDB(db)
	return p
}

type personnelClassDo struct{ gen.DO }

func (p personnelClassDo) Debug() *personnelClassDo {
	return p.withDO(p.DO.Debug())
}

func (p personnelClassDo) WithContext(ctx context.Context) *personnelClassDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personnelClassDo) ReadDB() *personnelClassDo {
	return p.Clauses(dbresolver.Read)
}

func (p personnelClassDo) WriteDB() *personnelClassDo {
	return p.Clauses(dbresolver.Write)
}

func (p personnelClassDo) Session(config *gorm.Session) *personnelClassDo {
	return p.withDO(p.DO.Session(config))
}

func (p personnelClassDo) Clauses(conds ...clause.Expression) *personnelClassDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personnelClassDo) Returning(value interface{}, columns ...string) *personnelClassDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personnelClassDo) Not(conds ...gen.Condition) *personnelClassDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personnelClassDo) Or(conds ...gen.Condition) *personnelClassDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personnelClassDo) Select(conds ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personnelClassDo) Where(conds ...gen.Condition) *personnelClassDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personnelClassDo) Order(conds ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personnelClassDo) Distinct(cols ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personnelClassDo) Omit(cols ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personnelClassDo) Join(table schema.Tabler, on ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personnelClassDo) LeftJoin(table schema.Tabler, on ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personnelClassDo) RightJoin(table schema.Tabler, on ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personnelClassDo) Group(cols ...field.Expr) *personnelClassDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personnelClassDo) Having(conds ...gen.Condition) *personnelClassDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personnelClassDo) Limit(limit int) *personnelClassDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personnelClassDo) Offset(offset int) *personnelClassDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personnelClassDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *personnelClassDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personnelClassDo) Unscoped() *personnelClassDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personnelClassDo) Create(values ...*isa95.PersonnelClass) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personnelClassDo) CreateInBatches(values []*isa95.PersonnelClass, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personnelClassDo) Save(values ...*isa95.PersonnelClass) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personnelClassDo) First() (*isa95.PersonnelClass, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelClass), nil
	}
}

func (p personnelClassDo) Take() (*isa95.PersonnelClass, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelClass), nil
	}
}

func (p personnelClassDo) Last() (*isa95.PersonnelClass, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelClass), nil
	}
}

func (p personnelClassDo) Find() ([]*isa95.PersonnelClass, error) {
	result, err := p.DO.Find()
	return result.([]*isa95.PersonnelClass), err
}

func (p personnelClassDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*isa95.PersonnelClass, err error) {
	buf := make([]*isa95.PersonnelClass, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personnelClassDo) FindInBatches(result *[]*isa95.PersonnelClass, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personnelClassDo) Attrs(attrs ...field.AssignExpr) *personnelClassDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personnelClassDo) Assign(attrs ...field.AssignExpr) *personnelClassDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personnelClassDo) Joins(fields ...field.RelationField) *personnelClassDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personnelClassDo) Preload(fields ...field.RelationField) *personnelClassDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personnelClassDo) FirstOrInit() (*isa95.PersonnelClass, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelClass), nil
	}
}

func (p personnelClassDo) FirstOrCreate() (*isa95.PersonnelClass, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*isa95.PersonnelClass), nil
	}
}

func (p personnelClassDo) FindByPage(offset int, limit int) (result []*isa95.PersonnelClass, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personnelClassDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personnelClassDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personnelClassDo) Delete(models ...*isa95.PersonnelClass) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personnelClassDo) withDO(do gen.Dao) *personnelClassDo {
	p.DO = *do.(*gen.DO)
	return p
}
